#!/usr/bin/env python3

# Copyright (c) A Christison 2025 All Rights Reserved.

"""AIMPRO potential 2 cube passer: aimpot2cube [options] AIMPRO_output_file [grid_vectors_input_file]

This script converts AIMRPO atomic positions to the atomic reference frame, using Jon Goss's gres script.

Perl scripts
gres: https://www.staff.ncl.ac.uk/j.p.goss/MMG/Scripts/Output.html
(Copyright (c) J.P. Goss 2024 All Rights Reserved.)

Due to limitations of gres -einit this script is unable to convert to/from the scaled atomic reference frame.

TODO Add further description here

CUBE file format documentation: https://paulbourke.net/dataformats/cube/

[options]
-h, --help: display help dialogue
-v, --verbose: Enables verbose output

AIMPRO_output_file
Output file from AIMPRO potential job

AIMPRO potential job documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html

The atomic positions in the potential job MUST be defined in au i.e. begin[atomic]{positions} MUST be specified.

any2atomic can be used to convert the atom positions in a dat file to the atomic reference frame from any other reference frame.

Atom positions documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/positions.html

[grid_vectors_input_file]

NOTE: this file must be the same as the one used by potfileGen

If no grid_vectors_input_file is specified the default input file from common_io will be used. This file is user editable (advanced: see ./low_level_scripts/python/common_io.py).

Specifies the vectors & their repeats defining the grid.
The file is delimited by whitespace and has the format:

Repeats_A(int) A_x(float) A_y(float) A_z(float)
Repeats_B(int) B_x(float) B_y(float) B_z(float)
Repeats_C(int) C_x(float) C_y(float) C_z(float)

Floats are in 12.6 format.

Known issues:
None
"""

import argparse
from pathlib import Path
import numpy as np
import common_io  as cio
import fnmatch
import subprocess
import methods as m
import const as c
import re

# Module development info
VERSION_NUMBER = "0.1"
VERSION_DATE = "15/08/2025"
AUTHORS = "Alex Christison"
COPYRIGHT = "Copyright (c) A Christison 2025 All Rights Reserved"

# Perl script path details
PERL_PATH = Path(__file__).resolve().parent  / "low_level_scripts" / "perl" # !!!Note __file__ isn't always safe, e.g. in non-local imported modules!!!
RGRES_PATH = PERL_PATH / "rgres"

def read_commmand_line() -> tuple[str, str]:
    """Gets input filename(s).

    If no input file is provided in command line the default input file is used.

    Sets global verbose output flag if specified in cmd line args.

    Args:
        None

    Returns:
        grid_vec_infile: Filename of grid vectors input file
        aimpro_infile: Filename of AIMPRO potential job output

    Raises:
        Errors & exits with message if incorrect number of args detected.
        Errors & exits with message if provided input file does not exist.
        Warns if AIMPRO output file does not match conventional AIM.sh.o* format.
    """
    global verbose_output

    parser = argparse.ArgumentParser(
                    prog = "aimpot2cube",
                    formatter_class=argparse.RawDescriptionHelpFormatter,
                    description = "Pass the output of an AIMPRO potential job to the .cbue file format.\n\nAIMPRO potential job documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html\n\n .cube file format: https://paulbourke.net/dataformats/cube/",
                    epilog = f"Version info\n\nAuthor(s): {AUTHORS} \nVersion: {VERSION_NUMBER} \nDate: {VERSION_DATE} \n\n{COPYRIGHT}.")

    parser.add_argument("-v", "--verbose",
                        action = "store_true",
                        help = "turn on verbose output mode")

    parser.add_argument("aimpro_output_file",
                        nargs = 1,
                        help = "the AIM.sh.o* output file from an AIMPRO potential job")

    parser.add_argument("grid_vectors_input_file",
                        nargs = "?",
                        default = cio.DEFAULT_POT_INPUT_FILENAME,
                        help = f"input file, if none specified the default input file is used: {cio.DEFAULT_POT_INPUT_FILENAME}")

    args = parser.parse_args()
    verbose_output = args.verbose
    aimpro_infile = args.aimpro_output_file[0]
    grid_vec_infile = args.grid_vectors_input_file

    # Check provided files are valid
    if not Path(aimpro_infile).is_file():
        raise FileNotFoundError(f"no such file - '{aimpro_infile}'")
    if not Path(grid_vec_infile).is_file():
        raise FileNotFoundError(f"no such file - '{grid_vec_infile}'")

    # Check if AIMPRO file has correct naming convention, warn if not
    if not fnmatch.fnmatch(aimpro_infile ,"AIM.sh.o*"):
        print(f"Warning: {aimpro_infile} filename does not match the conventional AIMPRO output filename format (AIM.sh.o*), are you sure it is an AIMPRO output file?")

    if verbose_output:
        print("Verbose output on.\n")
        print(f"Input file: {grid_vec_infile}\n")

    return grid_vec_infile, aimpro_infile

def generate_grid_points(repeats: object, vectors: object) -> object:
    """Generates the pot_file grid points and adds adds them to a numpy array.

    Args:
        repeats: number of repeats of each vector
        vectors: grid vectors

    Returns:
        grid_points: numpy array of generated grid points

    Raises:
        None
    """

    # Get required array length
    num_grid_points = np.prod(repeats)
    grid_points = np.zeros((num_grid_points, 3))

    # Declare  row counter
    row_count = 0

    for ia in range(0, repeats[0]):
        for ib in range(0, repeats[1]):
            for ic in range(0, repeats[2]):

                # Calculate grid point and add to array
                grid_points[row_count, :] = ia * vectors[0, :] \
                                    + ib * vectors[1, :] \
                                    + ic * vectors[2, :]
                # Increment row counter
                row_count+=1

    return grid_points

def get_atom_positions(aim_file: str) -> tuple[object, object]:
    """Uses Jon Gos's gres on the backend to extract atom positions in atomic units and the species index list.

    gres: https://www.staff.ncl.ac.uk/j.p.goss/MMG/Scripts/Output.html
    (Copyright (c) J.P. Goss 2024 All Rights Reserved.)

    Args:
        aim_file: AIMPRO output filename

    Returns:
        species_ind: array of species indexs (column 2 of OTB)
        atom_pos: atom positions in au (columns 5-9 of OTB)

    Raises:
        Warns if the files it needs to create already exist & backs up the existing ones
    """

    # Ensure we are able to create the xyz & otb files we temporarily need, backup exisiting ones and inform user
    if Path(f"xyz.{aim_file}.init").is_file():
        subprocess.run(f"mv xyz.{aim_file}.init xyz.{aim_file}.init.bak", shell=True, check=True)
        print(f"Warning: exisiting xyz.{aim_file}.init moved to xyz.{aim_file}.init.bak\n")

    if Path(f"otb.xyz.{aim_file}.init").is_file():
        subprocess.run(f"mv otb.xyz.{aim_file}.init otb.xyz.{aim_file}.init.bak", shell=True, check=True)
        print(f"Warning: exisiting otb.xyz.{aim_file}.init moved to otb.xyz.{aim_file}.init.bak\n")

    # Convert dat file to xyz
    subprocess.run(f"{RGRES_PATH} -einit {aim_file} 1> /dev/null", shell=True, check=True)

    # Convert xyz to otb, positions are now in atomic
    subprocess.run(f"{RGRES_PATH} -x2o xyz.{aim_file}.init 1> /dev/null", shell=True, check=True)

    # Read in otb values, they will be in the atomic reference frame
    result = m.read_otb(f"otb.xyz.{aim_file}.init")

    # Only need species_index and atom positions
    species_ind = result[0]
    atom_pos = result[2]

    # Remove temporary xyz & otb files
    subprocess.run(f"rm xyz.{aim_file}.init  otb.xyz.{aim_file}.init", shell=True, check=True)

    return species_ind, atom_pos

def read_aimpro_infile(aimpro_output_file: str, grid_vectors_input_file: str,  repeats: object, validation_grid_points: object) -> tuple[int, list, object, object]:
    """Reads AIMPRO output file and extracts required data

    Args:
        aimpro_output_file: AIMPRO potential job output file name
        grid_vectors_input_file: : Filename of grid vectors input file
        validation_grid_points: numpy array of regenerated grid points for validation of those in the AIMPRO file
        repeats: number of repeats of each grid defining vector

    Returns:
        num_atoms: integer number of atoms (omiting ghost atoms)
        species_list: list of species symbols
        atom_pos: atom positions in au (omiting ghost atoms)
        potental_values: sum of the 3 potenial values from aimpro_output_file

    Raises:
        Errors and exits if species with partial protons detected
        Errors and exits if number of grid points doesn't match those regenerated
        Errors and exits if grid points in AIMPRO file don't match the regenerated grid points from the grid vectors file
    """

    # TODO Read file in line by line and extract required quantities, error if not a potential job

    #TODO required quantities - Number of atoms, scale, atom positions & reference (au only - error if not), atom types from psuedoes, potential data (sum of all 3 contributions) - ensure to populate data structure in the same order that data was written in to preserve indices - regex potentials label, then read in as many lines as num_grid_points (np.prod(repeats) specifies?

    # TODO Check gridpoints from AIMPRO file match those from provided grid vectors input file (to precisions dictated by the AIMPRO output) if not, error out

    # TODO replace atom type enumerator with chemical symbol from psuedoes (index 1 = 1st in species list etc) - error check for 1.x Hydrogen, omit GHOST atoms and give prinout to update user, count number of GHOSTs, strip GHOSTs from atom positions and species list

    # Initalise proton num array
    species_proton_num_list = []

    # Initalise flags and values for the potential job
    potental_job_run = False
    in_potential_output = False

    expected_lines_of_pot = np.prod(repeats)
    pot_count = 0

    aim_grid_points = np.zeros((expected_lines_of_pot, 3))
    aim_pot_values = np.zeros((expected_lines_of_pot))

    # Open AIMPRO file, read line by line and extract data
    with open(aimpro_output_file,"r") as infile:
        for line in infile:

            # Skip comment lines
            if re.search(c.RE_AIM_COMMENT, line):
                continue

            # Check we are not in scaled atomic reference frame
            if re.search(c.RE_SCALE_POSLINE_START, line):
                raise Exception(f"incorrect input format in {aimpro_infile} - unable to convert coordinates that are in the scaled atomic reference frame")

            # Error if species with partial protons detected
            if re.search(c.RE_PARTIAL_PROTONS, line):
                raise Exception(f"unphysical input in {aimpro_output_file} - unable to parse Hydrogen species with partial protons")

            species_search = re.search(c.RE_SPECIES_EXTRACT, line)
            ghost_search = re.search(c.RE_GHOST, line)
            pot_header_search = re.search(c.RE_POTENTIALS_HEADER, line)

            # Extract proton number of species and add to list in order (including GHOST atoms, we will filter them out later)
            if species_search:
                species_proton_num_list.append(int(species_search.group(1)))

                if verbose_output:
                    print(f"Species of type {species_search.group(2)} detected\n")

            if ghost_search:
                species_proton_num_list.append(int(ghost_search.group(1)))

                if verbose_output:
                    print(f"Species of type {ghost_search.group(2)} detected\n")

            # Set flags to True to indicate this was a potential job, and we are in the potental region
            if not potental_job_run and not in_potential_output and pot_header_search:
                potental_job_run = True
                in_potential_output = True
                continue

            # We are in the potenial region, so record data
            if in_potential_output:

                # If we have already read in as many lines of potenial as we expect, check that the next line is empty.
                # If it isn't there is more data than we are expecting and something has gone wrong
                if pot_count == expected_lines_of_pot:

                    if line == "\n": # Line at the end of potential output is a new line char
                        in_potential_output = False
                        continue
                    else:
                        raise Exception(f"more potenial output detected in {aimpro_output_file} than expected from {grid_vectors_input_file} - are you sure {grid_vectors_input_file} is the correct file?")

                # Increment count of number of lines we have read in
                pot_count+=1


    # Error if we haven't detected a potental job run, looks like AIMPRO file wasn't a potenial job output
    if not potental_job_run:
        raise Exception(f"no potenial output detected in {aimpro_output_file} - are you sure it is an AIMPRO potential job output?")

    print(species_proton_num_list)

    # Get species index list and atom positions in atomic units
    species_index, atom_positions = get_atom_positions(aimpro_output_file)

    # Remove ghost atoms

    # Now that we have removed any ghost atoms, we can count how many atoms we have
    num_atoms = atom_positions.shape[0]

    potental_values = np.zeros((3, 3))

    return num_atoms, species_proton_num_list, atom_positions, potental_values

def write_cube_file(aimpro_output_file: str, grid_vectors_input_file: str, num_atoms: int, species_proton_num_list: object, atom_pos: object, potental_values: object, repeats: object, vectors: object) -> None:
    """Generates and writes out pot_file.cube .

    Args:
        aimpro_output_file: AIMPRO potential job output file name
        grid_vectors_input_file: Grid vectors input filename/path
        num_atoms: integer number of atoms (omiting ghost atoms)
        species_proton_num_list: list of species symbols proton numbers (omiting ghost atoms)
        atom_pos: atom positions in au (omiting ghost atoms)
        potental_values: sum of the 3 potenial values from aimpro_output_file
        repeats: number of repeats of each grid defining vector
        vectors: grid vectors

    Returns:
        None

    Raises:
        None
    """

    # Open an outfile in cwd
    # (N.B. this is the directory aimpot2cube was called from, not were it lives)
    cube_output_file = aimpro_output_file + cio.CUBE_OUTPUT_FILENAME
    outpath = Path.cwd() / cube_output_file

    if verbose_output:
        print(f"Writing output to file: {outpath}\n")

    # Open output file
    with open(outpath,"w") as outfile:

        # Fill the required comment lines in .cube file
        outfile.write("Cubefile created from AIMPRO output using aimpot2cube parser: Copyright (c) A Christison 2025 All Rights Reserved.\n")
        outfile.write(f"Contains the total potential from {aimpro_output_file} on a voxelised mapping of the grid specified in {grid_vectors_input_file}\n")

        # TODO Add writing of output file here

        # TODO write quantites as required including loop format specified in: https://paulbourke.net/dataformats/cube/

        if verbose_output:
            print(f"Finished writing to: {outpath}\n")

def main() -> None:

    # Read cmd line for input files
    gv_infile, aim_infile = read_commmand_line()

    # Get repeats, vectors and generate grid points dataframe from grid vectors input file
    rep, vec = cio.read_grid_vectors(gv_infile, verbose_output)

    # Generate grid points from grid vectors, used later to valadate grid in AIMPRO input file
    pts = generate_grid_points(rep,vec)

    # Read in AIMPRO file and extract required data
    natoms, species_pn, atpos, pots = read_aimpro_infile(aim_infile, gv_infile, rep, pts)

    # Write cube file
    write_cube_file(aim_infile, gv_infile, natoms, species_pn, atpos, pots, rep, vec)

if __name__ == "__main__":
    main()
