#!/usr/bin/env python3

# Copyright (c) A Christison 2025 All Rights Reserved.

"""AIMPRO potential 2 cube passer: aimpot2cube [options] AIMPRO_output_file [grid_vectors_input_file]

TODO Add further description here

CUBE file format documentation: https://paulbourke.net/dataformats/cube/

[options]
-h, --help: display help dialogue
-v, --verbose: Enables verbose output

AIMPRO_output_file
Output file from AIMPRO potential job

AIMPRO potential job documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html

The atomic positions in the potential job MUST be defined in au i.e. begin[atomic]{positions} MUST be specified.

any2atomic can be used to convert the atom positions in a dat file to the atomic reference frame from any other reference frame.

Atom positions documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/positions.html

[grid_vectors_input_file]

NOTE: this file must be the same as the one used by regGridPlot

If no grid_vectors_input_file is specified the default input file from common_io will be used. This file is user editable (advanced: see ./low_level_scripts/python/common_io.py).

Specifies the vectors & their repeats defining the grid.
The file is delimited by whitespace and has the format:

Repeats_A(int) A_x(float) A_y(float) A_z(float)
Repeats_B(int) B_x(float) B_y(float) B_z(float)
Repeats_C(int) C_x(float) C_y(float) C_z(float)

Floats are in 12.6 format.

Known issues:
None
"""

import argparse
import sys
import os
import numpy as np
import common_io  as cio
import fnmatch

# Module development info
VERSION_NUMBER = "0.1"
VERSION_DATE = "15/08/2025"
AUTHORS = "Alex Christison"
COPYRIGHT = "Copyright (c) A Christison 2025 All Rights Reserved"

def read_commmand_line() -> str:
    """Gets input filename(s).

    If no input file is provided in command line the default input file is used.

    Sets global verbose output flag if specified in cmd line args.

    Args:
        None

    Returns:
        input_filename: Filename of input file

    Raises:
        Errors & exits with message if incorrect number of args detected.
        Errors & exits with message if provided input file does not exist.
        Warns if AIMPRO output file does not match conventional AIM.sh.o* format.
    """
    global verbose_output

    parser = argparse.ArgumentParser(
                    prog = "aimpot2cube",
                    formatter_class=argparse.RawDescriptionHelpFormatter,
                    description = "Pass the output of an AIMPRO potential job to the .cbue file format.\n\nAIMPRO potential job documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html\n\n .cube file format: https://paulbourke.net/dataformats/cube/",
                    epilog = f"Version info\n\nAuthor(s): {AUTHORS} \nVersion: {VERSION_NUMBER} \nDate: {VERSION_DATE} \n\n{COPYRIGHT}.")

    parser.add_argument("-v", "--verbose",
                        action = "store_true",
                        help = "turn on verbose output mode")

    parser.add_argument("aimpro_output_file",
                        nargs = 1,
                        help = "the AIM.sh.o* output file from an AIMPRO potential job")

    parser.add_argument("grid_vectors_input_file",
                        nargs = "?",
                        default = cio.DEFAULT_POT_INPUT_FILENAME,
                        help = f"input file, if none specified the default input file is used: {cio.DEFAULT_POT_INPUT_FILENAME}")

    args = parser.parse_args()
    verbose_output = args.verbose
    aimpro_infile = args.aimpro_output_file[0]
    grid_vec_infile = args.grid_vectors_input_file

    # Check provided files are valid
    if not os.path.isfile(aimpro_infile):
        raise FileNotFoundError(f"no such file - '{aimpro_infile}'")
    if not os.path.isfile(grid_vec_infile):
        raise FileNotFoundError(f"no such file - '{grid_vec_infile}'")

    # Check if AIMPRO file has correct naming convention, warn if not
    if not fnmatch.fnmatch(aimpro_infile ,"AIM.sh.o*"):
        print(f"Warning: {aimpro_infile} filename does not match the conventional AIMPRO output filename format (AIM.sh.o*), are you sure it is an AIMPRO output file?")

    if verbose_output:
        print("Verbose output on.\n")
        print(f"Input file: {grid_vec_infile}\n")

    return grid_vec_infile, aimpro_infile

def generate_grid_points(repeats: object, vectors: object) -> object:
    """Generates the pot_file grid points and adds adds them to a numpy array.

    Args:
        repeats: number of repeats of each vector
        vectors: grid vectors

    Returns:
        grid_points: numpy array of generated grid points

    Raises:
        None
    """

    # Get required array length
    num_grid_points = np.prod(repeats)
    grid_points = np.zeros((num_grid_points, 3))

    # Declare  row counter
    row_count = 0

    for ia in range(0, repeats[0]):
        for ib in range(0, repeats[1]):
            for ic in range(0, repeats[2]):

                # Calculate grid point and add to array
                grid_points[row_count, :] = ia * vectors[0, :] \
                                    + ib * vectors[1, :] \
                                    + ic * vectors[2, :]
                # Increment row counter
                row_count+=1

    return grid_points

def read_aimpro_infile(aimpro_output_file: str) -> object:
    """Read AIMPRO output fule and extracts required data

    Args:
        aimpro_output_file: AIMPRO potential job output file name

    Returns:
        num_atoms: integer number of atoms (omiting ghost atoms)
        species_list: list of species symbols
        atom_pos: atom positions in au (omiting ghost atoms)
        potental_values: sum of teh 3 potenial values from aimpro_output_file

    Raises:
        None
    """

    # TODO Read file in line by line and extract required quantities, error if not a potential job

    #TODO required quantities - Number of atoms, scale, atom positions & reference (au only - error if not), atom types from psuedoes, potential data (sum of all 3 contributions) - ensure to populate data structure in the same order that data was written in to preserve indices - regex potentials label, then read in as many lines as num_grid_points (np.prod(repeats) specifies?

    # TODO Check gridpoints from AIMPRO file match those from provided grid vectors input file (to precisions dictated by the AIMPRO output) if not, error out

    # TODO replace atom type enumerator with chemical symbol from psuedoes (index 1 = 1st in species list etc) - error check for 1.x Hydrogen, omit GHOST atoms and give prinout to update user, count number of GHOSTs, strip GHOSTs from atom positions and species list

    # TODO Update total number of atoms as new_tot = tot - num_GHOSTs

    num_atoms = 0
    species_list = [""]
    atom_pos = np.zeros(3)
    potental_values = np.zeros((3, 3))

    return num_atoms, species_list, atom_pos, potental_values

def write_cube_file(aimpro_output_file: str, grid_vectors_input_file: str, num_atoms: int, species_list: list, atom_pos: object, potental_values: object, repeats: object, vectors: object) -> None:
    """Generates and writes out pot_file.cube .

    Args:
        aimpro_output_file: AIMPRO potential job output file name
        grid_vectors_input_file: Grid vectors input filename/path
        num_atoms: integer number of atoms (omiting ghost atoms)
        species_list: list of species symbols
        atom_pos: atom positions in au (omiting ghost atoms)
        potental_values: sum of teh 3 potenial values from aimpro_output_file
        repeats: number of repeats of each vector
        vectors: grid vectors

    Returns:
        None

    Raises:
        None
    """

    # Open an outfile in cwd
    # (N.B. this is the directory aimpot2cube was called from, not were it lives)
    outpath = os.getcwd() + "/" + aimpro_output_file + cio.CUBE_OUTPUT_FILENAME

    if verbose_output:
        print(f"Writing output to file: {outpath}\n")

    # Open output file
    with open(outpath,"w") as outfile:

        # Fill the required comment lines in .cube file
        outfile.write("Cubefile created from AIMPRO output using aimpot2cube parser: Copyright (c) A Christison 2025 All Rights Reserved.\n")
        outfile.write(f"Contains the total potential from {aimpro_output_file} on a voxelised mapping of the grid specified in {grid_vectors_input_file}.\n")

        # TODO Add writing of output file here

        # TODO write quantites as required including loop format specified in: https://paulbourke.net/dataformats/cube/

        if verbose_output:
            print(f"Finished writing to: {outpath}\n")

def main() -> None:

    # Read cmd line for input files
    gv_infile, aim_infile = read_commmand_line()

    # Get repeats, vectors and generate grid points dataframe from grid vectors input file
    rep, vec = cio.read_grid_vectors(gv_infile)

    # Generate grid points from grid vectors, used later to valadate grid in AIMPRO input file
    pts = generate_grid_points(rep,vec)

    # Read in AIMPRO file and extract required data
    natoms, species, atpos, pots = read_aimpro_infile(aim_infile)

    # Write cube file
    write_cube_file(aim_infile, gv_infile, natoms, species, atpos, pots, rep, vec)

if __name__ == "__main__":
    main()
