#!/usr/bin/env python3

# Copyright (c) A Christison 2025 All Rights Reserved.

"""apac2apac [options] (--atomic | --intp | --angstroms | --intc) dat_file

This script converts AIMRPO atomic positions using any valid selection of reference frame to any other any valid selection of reference frame based on user selection, using Jon Goss's gres, InsertOTB & otb2intp Perl scripts.

Atom positions documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/positions.html

Perl scripts
gres: https://www.staff.ncl.ac.uk/j.p.goss/MMG/Scripts/Output.html
InsertOTB: https://www.staff.ncl.ac.uk/j.p.goss/MMG/Scripts/OTB+XYZ.html
otb2intp: https://www.staff.ncl.ac.uk/j.p.goss/MMG/Scripts/DataFiles.html
(Copyright (c) J.P. Goss 2024, 2015, 2011 All Rights Reserved.)

[options]
-h, --help: display help dialogue
-rb, --retain_bak: Retains backup copy of datafile (dat_file.bak)

(--atomic | --intp | --intc | --angstroms)
-au, --atomic: convert to atomic reference frame
-p, --intp: convert to int-p reference frame
-ang, --angstroms: convert to angstroms reference frame
-c, --intc: convert to int-c reference frame


The above options are mutually exclusive and required.

dat_file
AIMPRO dat file, this must follow the dat.xxx file name convention

Known issues:
The script is unable to account for depreciated definitions of the lattice parameters (e.g. a0=...) due to limitations of otb2intp.
As these are depreciated this is not expected to be a frequent issue, however, example files in the docs still use the a0 definition so care must be taken to change a0= to params= in lattice{} if using these.

Due to limitations of gres -einit this script is unable to convert to/from the scaled atomic reference frame.
"""

import subprocess
import argparse
import fnmatch
from pathlib import Path
import methods as m
import const as c
import re

# Module development info
VERSION_NUMBER = "0.3"
VERSION_DATE = "20/08/2025"
AUTHORS = "Alex Christison"
COPYRIGHT = "Copyright (c) A Christison 2025 All Rights Reserved"

# Perl script path details
PERL_PATH = Path(__file__).resolve().parent  / "low_level_scripts" / "perl" # !!!Note __file__ isn't always safe, e.g. in non-local imported modules!!!
RGRES_PATH = PERL_PATH / "rgres"
CINSERTOTB_PATH = PERL_PATH / "cInsertOTB"
COTB2INTP_PATH = PERL_PATH / "cotb2intp"
COTB2INTC_PATH = PERL_PATH / "cotb2intc"

def read_commmand_line() -> str:
    """Gets input filename,dat_file must follow the dat.xxx file name convention

    Args:
        None

    Returns:
        input_filename: Filename of input file

    Raises:
        Errors & exits with message if provided input file does not exist.
        Errors & exits with message if AIMPRO output file does not match conventional AIM.sh.o* format.
    """

    global retain_bak, do_atomic, do_intp, do_intc, do_ang, do_scale_val

    parser = argparse.ArgumentParser(
                    prog = "apac2apac",
                    formatter_class=argparse.RawDescriptionHelpFormatter,
                    description = "Converts atom positions in an AIMPRO dat file (dat_file) from any reference frame to any other using gres, InsertOTB & otb2intp.\n\nAtom positions documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/positions.html\n\ngres: https://www.staff.ncl.ac.uk/j.p.goss/MMG/Scripts/Output.html\nInsertOTB : https://www.staff.ncl.ac.uk/j.p.goss/MMG/Scripts/OTB+XYZ.html\notb2intp: https://www.staff.ncl.ac.uk/j.p.goss/MMG/Scripts/DataFiles.html\n(Copyright (c) J.P. Goss 2024, 2015, 2011 All Rights Reserved.)",
                    epilog = f"Version info\n\nAuthor(s): {AUTHORS} \nVersion: {VERSION_NUMBER} \nDate: {VERSION_DATE} \n\n{COPYRIGHT}.")

    parser.add_argument("-rb", "--retain_bak",
                        action = "store_true",
                        help = "retain backup of original dat_file (dat_file.bak)")

    group = parser.add_mutually_exclusive_group(required=True)

    group.add_argument("-au", "--atomic",
                        action = "store_true",
                        help = "convert to atomic reference frame")

    group.add_argument("-p", "--intp",
                        action = "store_true",
                        help = "convert to int-p reference frame")

    group.add_argument("-ang", "--angstroms",
                        action = "store_true",
                        help = "convert to angstroms reference frame")

    group.add_argument("-c", "--intc",
                        action = "store_true",
                        help = "convert to int-c reference frame")

    # Scale option disabled due to gres -einit bug
    # group.add_argument("-s", "--scale",
    #                     action = "store",
    #                     type=float,
    #                     default = False,
    #                     help = "convert to atomic reference frame, scaled by provided float value SCALE")

    parser.add_argument("dat_file",
                        nargs = 1,
                        help = f"AIMPRO dat file, must follow the dat.xxx file name convention")

    args = parser.parse_args()
    retain_bak = args.retain_bak
    input_filename = args.dat_file[0]
    do_atomic = args.atomic
    do_intp = args.intp
    do_ang = args.angstroms
    do_intc = args.intc

    # Stores both boolean flag & scale factor value as non-zero floats return True in boolean operations
    # Scale option disabled due to gres -einit bug
    # do_scale_val = args.scale
    do_scale_val = False

    # Check scale value isn't zero, if all do flags are false then scale = 0 must have been provided
    if not do_atomic and not do_intp and not do_intc and not do_ang and not do_scale_val:
        raise ValueError("user provded SCALE value cannot be 0.0")

    # Check provided file is valid
    if not Path(input_filename).is_file():
        raise FileNotFoundError(f"no such file - '{input_filename}'")

    # Check if AIMPRO dat file has correct naming convention, error if not
    if not fnmatch.fnmatch(input_filename ,"dat") or fnmatch.fnmatch(input_filename ,"dat.*"):
        raise Exception(f"incorrect file name convention - {input_filename} filename does not match AIMPRO dat file naming convention (dat.XXX)")

    # Check we are not in scaled atomic reference frame
    with open(input_filename,"r") as infile:
        for line in infile:
            if re.search(c.RE_SCALE_POSLINE_START, line):
                raise Exception(f"incorrect input format in {input_filename} - unable to convert coordinates that are in the scaled atomic reference frame")

    return input_filename

def convert_atomic_positions(input_file: str) -> None:
    """Converts positions in AIMPRO dat file to atomic

    Args:
        input_file: AIMPRO dat file

    Returns:
        None

    Raises:
        Warns if the files it needs to create already exist & backs up the existing ones
    """

    # Ensure we are able to create the xyz & otb files we temporarily need, backup exisiting ones and inform user
    if Path(f"xyz.{input_file}.init").is_file():
        subprocess.run(f"mv xyz.{input_file}.init xyz.{input_file}.init.bak", shell=True, check=True)
        print(f"Warning: exisiting xyz.{input_file}.init moved to xyz.{input_file}.init.bak\n")

    if Path(f"otb.xyz.{input_file}.init").is_file():
        subprocess.run(f"mv otb.xyz.{input_file}.init otb.xyz.{input_file}.init.bak", shell=True, check=True)
        print(f"Warning: exisiting otb.xyz.{input_file}.init moved to otb.xyz.{input_file}.init.bak\n")


    # Backup input dat file
    subprocess.run(f"cp {input_file} {input_file}.bak", shell=True, check=True)

    # Convert dat file to xyz
    subprocess.run(f"{RGRES_PATH} -einit {input_file} 1> /dev/null", shell=True, check=True)

    # Convert xyz to otb, positions are now in atomic
    subprocess.run(f"{RGRES_PATH} -x2o xyz.{input_file}.init 1> /dev/null", shell=True, check=True)

    # Rescaling needed in the following cases
    if do_ang or do_scale_val:

        # Read in otb values, they will be in the atomic reference frame
        species_index, nneigbour_map, atom_positions, species_string = m.read_otb(f"otb.xyz.{input_file}.init")


        # Rescale positions
        if do_ang:
            # Rescale
            atom_positions *= c.BOHR2ANG

        elif do_scale_val:
            # Rescale
            atom_positions *= do_scale_val

        # Write out rescaled otb
        m.write_otb(f"otb.xyz.{input_file}.init", species_index, nneigbour_map, atom_positions, species_string)


    # Insert positions into original dat file
    subprocess.run(f"{CINSERTOTB_PATH} otb.xyz.{input_file}.init {input_file}.bak > {input_file}", shell=True, check=True)

    # Reference frame changes
    if do_atomic or do_intp or do_intc:

        # Change reference setting in positions to atomic
        subprocess.run(f"sed -i 's/begin\\[.*\\]{{positions}}/begin\\[atomic\\]{{positions}}/g' {input_file}", shell=True, check=True)

    elif do_ang:

        # Change reference setting in positions to angstroms
        subprocess.run(f"sed -i 's/begin\\[.*\\]{{positions}}/begin\\[ang\\]{{positions}}/g' {input_file}", shell=True, check=True)

    elif do_scale_val:

        # Change reference setting in positions to the value of do_scale_val
        subprocess.run(f"sed -i 's/begin\\[.*\\]{{positions}}/begin\\[{do_scale_val}\\]{{positions}}/g' {input_file}", shell=True, check=True)


    # More steps to do if using internal coordinates
    if do_intp or do_intc:

        # Separate perl script screen printouts
        print("")

        if do_intp:

            # Convert atomic to int-p
            subprocess.run(f"{COTB2INTP_PATH} {input_file}", shell=True, check=True)

            # Separate perl script screen printouts
            print("")

            # Insert positions into original dat file
            subprocess.run(f"{CINSERTOTB_PATH} otb.intp {input_file} > {input_file}_tmp", shell=True, check=True)

            # Change reference setting in positions to int-p
            subprocess.run(f"sed -i 's/begin\\[.*\\]{{positions}}/begin\\[int-p\\]{{positions}}/g' {input_file}_tmp", shell=True, check=True)

            # Remove int-p otb file
            subprocess.run(f"rm otb.intp", shell=True, check=True)

        elif do_intc:

            # Convert atomic to int-c
            subprocess.run(f"{COTB2INTC_PATH} {input_file}", shell=True, check=True)

            # Separate perl script screen printouts
            print("")

            # Insert positions into original dat file
            subprocess.run(f"{CINSERTOTB_PATH} otb.intc {input_file} > {input_file}_tmp", shell=True, check=True)

            # Change reference setting in positions to int-p
            subprocess.run(f"sed -i 's/begin\\[.*\\]{{positions}}/begin\\[int-c\\]{{positions}}/g' {input_file}_tmp", shell=True, check=True)

            # Remove int-c otb file
            subprocess.run(f"rm otb.intc", shell=True, check=True)

        # Remove temporary dat file
        subprocess.run(f"mv {input_file}_tmp {input_file}", shell=True, check=True)

    # Remove temporary xyz & otb files
    subprocess.run(f"rm xyz.{input_file}.init  otb.xyz.{input_file}.init", shell=True, check=True)

    # if global retain_bak not flag set, delete bacupk dat file (dat_file.bak)
    if not retain_bak:
        subprocess.run(f"rm {input_file}.bak", shell=True, check=True)

    # Separate perl script screen printouts
    print("")

    # Inform user otb files have been removed to avoid confusion
    print("Temporary otb files removed\n")

    # Select coordinate type output text
    if do_atomic:
        coord_str = "atomic"
    elif do_intp:
        coord_str = "int-p"
    elif do_intc:
        coord_str = "int-c"
    elif do_ang:
        coord_str = "angstroms"
    elif do_scale_val:
        coord_str = "scaled atomic"
    else:
        # We shouldn't ever reach here!
        text = "ERROR!"

    # Print completion message
    print(f"Success! Atom positions written to {input_file} in the {coord_str} reference frame")

def main() -> None:

    # Read cmd line for input file
    filename = read_commmand_line()

    # Convert positions in dat_file to specified reference frame
    convert_atomic_positions(filename)

if __name__ == "__main__":
    main()
