#!/usr/bin/env python3

# Copyright (c) A Christison 2025 All Rights Reserved.

"""pot_file generator: potfile_gen [options] grid_vectors_input_file

This script plots a regular grid in the required format for the potential job in the AIMPRO code that is valid for cubefile plotting.

AIMPRO potential job documentation
https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html

Cubefile format
https://www.quantum-espresso.org/Doc/INPUT_PP.html (&PLOT namelist, iflag = 3, output_format = 6)
https://paulbourke.net/dataformats/cube/

The output pot_file is written to the current working directory

[options]
-h, --help: display help dialogue
-v, --verbose: turn on verbose output mode, this prints useful status info to screen
-d, --debug: turn on debug mode (for developers only)
-aif, --advanced-input-file: use the advanced grid vectors input file format (origin, repeats & grid vectors) rather than the current one
                        (number of points along vector & (supercell) real space lattice vectors) (see end of README for details)

grid_vectors_input_file
Specifies the vectors & the number of their repeats defining the grid of sampling points placed on the corner of each voxel of the parallelepiped plotting volume,
as well as the origin of the parallelepiped plotting volume, this can also be a filepath and/or compressed archive
(.bz2, .gz, .xz & .zst formats supported) to/of the file.

The file is delimited by whitespace and has the format:

Number_of_points_along_A(int)  A_x(float)  A_y(float)  A_z(float)
Number_of_points_along_B(int)  B_x(float)  B_y(float)  B_z(float)
Number_of_points_along_C(int)  C_x(float)  C_y(float)  C_z(float)

Where A, B & C are real space lattice vectors.

All vectors are in atomic units (i.e. Bohr).
These grids always originate at (0.0, 0.0, 0.0).

Number of points along a specified vector must be integers >= 1.
Vector components can have any valid float value.

Floats are in 12.6 format.

Much like MP k-point sampling, a suitably dense grid must be used for sampling the potential
to ensure suitable convergence.

The `-pci` or `--print-convergence-info` flag for the `aimpot2cube` parser enables the
printing of the volume averaged potential and maximum variation of the potential to screen,
these values can be used to convergence test the potential sampling grid densities.

The AIMPRO FFT grid density is the absolute maximum workable grid density,
by the nature of how FFT grids are used in DFT calculations densities higher than this
yield no improvement to the sampling accuracy.

The AIMPRO FFT grid density is often significantly more dense than required for applications
that use cubefile potential data, these higher densities have significantly higher file
storage (in the GB range) and AIMPRO runtime costs for no gain in scientific accuracy.

In testing AIMPRO potential jobs using the FFT grid density as the potential sampling density
# in the pot_file took 50x longer to run with files 60x larger than the correctly converged
potential sampling density for **No** improvement in scientific accuracy. As such it is
**strongly** advised users avoid the use of over-converged grid densities.

For computational expediency, it is recommended to converge the potential sampling grid
density on a unit cell of your system. Once converged, the number of sampling points along
each of your lattice vectors can then be up-scaled in kind with the up-scaled lattice
vectors when a supercell is produced from the unit cell.

Throughout this process an equal number of points/bohr along each vector must be maintained.

For example for lattice vectors with a a ratio of A:B:2C, there must be twice as many
points along C as A & B for any & all sampling densities. In this case 1:1:2 is the sparsest
grid that can be can used. This ratio can be checked against the FFT grid density as it
will have the correct ratio of points along each direction. In this example the converged
potential sampling grid density will be somewhere between 1:1:2 and the FFT grid density,
generally on the sparser end rather than the denser so it is advised convergence testing
is carried out going from sparse to dense grids.

Once the converged potential sampling grid density for your unit cell has been found,
the number of points along each lattice vector must be scaled up in accordance with the
supercell size. If for the previous example of lattice vectors in the ratio A:B:2C,
lattice vectors A & B increase by 4x the number of potential sampling points along A & B
must increase by 4x to keep the number of sampling points/bohr consistent along each lattice
vector. Here no scaling will be applied to the number of potential sampling points along C,
as C didn't change when producing a supercell.

For the case of example_input.in, it is designed around a 1x1x1 simple cubic diamond system
with a lattice constant of 6.74 Bohr and a converged sampling density with 10 potential
sampling points along all vectors of the cell.

The (supercell) real space lattice vectors for a given cell geometry can be found by searching
a corresponding AIMPRO output/ PAIM output for: ` unit vectors : real space`

e.g.:

 unit vectors : real space, reciprocal space
     6.74000     0.00000     0.00000          0.93222     0.00000     0.00000
     0.00000     6.74000     0.00000          0.00000     0.93222     0.00000
     0.00000     0.00000     6.74000          0.00000     0.00000     0.93222

Combining the real space lattice vectors and sampling density gives an input file of the form:

10 6.74 0.00 0.00
10 0.00 6.74 0.00
10 0.00 0.00 6.74

Known issues:
None
"""

# System modules
import argparse
from pathlib import Path
import sys
from typing import IO, Optional

# Third party modules
import numpy as np

# First party modules
import common_io as cio

# Module development info
VERSION_NUMBER = "1.0"                                              #pylint: disable=duplicate-code
VERSION_DATE = "16/12/2025"                                         #pylint: disable=duplicate-code
AUTHORS = "Alex Christison"                                         #pylint: disable=duplicate-code
COPYRIGHT = "Copyright (c) A Christison 2025 All Rights Reserved"   #pylint: disable=duplicate-code

def read_commmand_line() -> Optional[IO[str]]:
    """Gets input filename

    If no input file is provided in command line the default input file is used.

    Sets global verbose output flag if specified in cmd line args.

    Args:
        None

    Returns:
        input_filename: Filename of input file

    Raises:
        Errors & exits with message if incorrect number of args detected.
        Errors & exits with message if provided input file does not exist.
    """
    global verbose_output, debug, use_advanced_input_format

    parser = argparse.ArgumentParser(
                    prog = "potfile_gen",
                    formatter_class=argparse.RawDescriptionHelpFormatter,
                    description = "Plot a regular grid for the AIMPRO potential job. \
                                    \n\nAIMPRO potential job documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html",
                    epilog = f"Version info\n\nAuthor(s): {AUTHORS} \nVersion: {VERSION_NUMBER} \nDate: {VERSION_DATE} \n\n{COPYRIGHT}.") #pylint: disable=duplicate-code

    parser.add_argument("-v", "--verbose",                                                                              #pylint: disable=duplicate-code
                        action = "store_true",                                                                          #pylint: disable=duplicate-code
                        default = False,                                                                                #pylint: disable=duplicate-code
                        help = "turn on verbose output mode, this prints useful status info to screen")                 #pylint: disable=duplicate-code

    parser.add_argument("-d", "--debug",                                                                                #pylint: disable=duplicate-code
                        action = "store_true",                                                                          #pylint: disable=duplicate-code
                        default = False,                                                                                #pylint: disable=duplicate-code
                        help = "turn on debug mode (for developers only)")                                              #pylint: disable=duplicate-code

    parser.add_argument("-aif", "--advanced-input-file",                                                                   #pylint: disable=duplicate-code
                        action = "store_true",                                                                          #pylint: disable=duplicate-code
                        default = False,                                                                                #pylint: disable=duplicate-code
                        dest = "advanced_input_file",
                        help = "use the advanced grid vectors input file format (orign, repeats & grid vectors) \
                                rather than the current one (number of points along vector & (supercell) real space lattice vectors)")   #pylint: disable=duplicate-code

    parser.add_argument("grid_vectors_input_file",
                        nargs = 1,
                        help = "grid vectors input file, this can also be a filepath and/or compressed archive to/of the file")

    args = parser.parse_args()
    verbose_output = args.verbose
    debug = args.debug
    use_advanced_input_format = args.advanced_input_file
    input_filename = args.grid_vectors_input_file[0]

    # Disable traceback when not in debug mode
    if not debug:
        sys.tracebacklimit = 0

    # Check provided file is valid
    if not Path(input_filename).is_file():
        raise FileNotFoundError(f"no such file - '{input_filename}'")

    if verbose_output:
        print("Verbose output mode enabled\n")
        print(f"Input file: {input_filename}\n")

    return input_filename

def write_pot_file(grid_points: object, num_grid_points: int) -> None:
    """Generates and writes out AIMPRO pot_file

    Args:
        repeats: number of repeats of each vector
        vectors: grid vectors
        origin: parallelepiped grid origin

    Returns:
        None

    Raises:
        None
    """

    # Get output file path
    # (N.B. this is the directory potfile_gen was called from, not where it lives)
    outpath = Path.cwd() / cio.POT_OUTPUT_FILENAME

    if verbose_output:
        print(f"Writing output to file: {outpath}\n")

    np.savetxt(outpath, grid_points, fmt="%12.6f", header= str(num_grid_points), comments='')

    if verbose_output:
        print(f"Finished writing to: {outpath}")

def main() -> None:
    """Main method

    The main method is run when executing the prog.py file from console.

    This method is not designed to be called like a method from a module.
    """

    # Read cmd line for input file
    filename = read_commmand_line()

    # Get repeats and vectors from input file
    if use_advanced_input_format:
        rep, vec, orig = cio.read_grid_vectors_advanced_input(filename, verbose_output)
    else:
        rep, vec, orig = cio.read_grid_vectors(filename, verbose_output)

    # Generate grid points
    g_pts, num_g_pts = cio.generate_grid_points(rep, vec, orig, verbose_output)

    # Write grid using vectors & their repeats
    write_pot_file(g_pts, num_g_pts)

if __name__ == "__main__":
    main()
