#!/usr/bin/env python3

# Copyright (c) A Christison 2025 All Rights Reserved.

"""pot_file generator: potfileGen [options] [grid_vectors_input_file]

This script plots a regular grid in the required format for the potential job in the AIMPRO code.

AIMPRO potential job documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html

The output pot_file is written to the current working directory

If no input file is specified the default input file from common_io will be used. This file is user editable (advanced: see ./low_level_scripts/python/common_io.py).

[options]
-h, --help: display help dialogue
-v, --verbose: turn on verbose output mode
-d, --debug: turn on debug mode (for developers only)

[grid_vectors_input_file]
Specifies the vectors & their repeats defining the grid.
The file is delimited by whitespace and has the format:

Repeats_A(int) A_x(float) A_y(float) A_z(float)
Repeats_B(int) B_x(float) B_y(float) B_z(float)
Repeats_C(int) C_x(float) C_y(float) C_z(float)

Repeats values must be >= 1.
Vector compoment values must be >= 0.0.

Floats are in 12.6 format.

Known issues:
None
"""

import argparse
from pathlib import Path
import numpy as np
import common_io as cio
import sys

# Module development info
VERSION_NUMBER = "0.1"
VERSION_DATE = "11/08/2025"
AUTHORS = "Alex Christison"
COPYRIGHT = "Copyright (c) A Christison 2025 All Rights Reserved"

def read_commmand_line() -> str:
    """Gets input filename

    If no input file is provided in command line the default input file is used.

    Sets global verbose output flag if specified in cmd line args.

    Args:
        None

    Returns:
        input_filename: Filename of input file

    Raises:
        Errors & exits with message if incorrect number of args detected.
        Errors & exits with message if provided input file does not exist.
    """
    global verbose_output, debug

    parser = argparse.ArgumentParser(
                    prog = "potfileGen",
                    formatter_class=argparse.RawDescriptionHelpFormatter,
                    description = "Plot a regular grid for the AIMPRO potential job.\n\nAIMPRO potential job documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html",
                    epilog = f"Version info\n\nAuthor(s): {AUTHORS} \nVersion: {VERSION_NUMBER} \nDate: {VERSION_DATE} \n\n{COPYRIGHT}.")

    parser.add_argument("-v", "--verbose",
                        action = "store_true",
                        help = "turn on verbose output mode")

    parser.add_argument("-d", "--debug",
                        action = "store_true",
                        default = False,
                        help = "turn on debug mode (for developers only)")

    parser.add_argument("grid_vectors_input_file",
                        nargs = "?",
                        default = cio.DEFAULT_POT_INPUT_FILENAME,
                        help = f"grid vectors input file, if none specified the default input file is used: {cio.DEFAULT_POT_INPUT_FILENAME}")

    args = parser.parse_args()
    verbose_output = args.verbose
    debug = args.debug
    input_filename = args.grid_vectors_input_file

    # Disable traceback when not in debug mode
    if not debug:
        sys.tracebacklimit = 0

    # Check provided file is valid
    if not Path(input_filename).is_file():
        raise FileNotFoundError(f"no such file - '{input_filename}'")

    if verbose_output:
        print("Verbose output mode enabled\n")
        print(f"Input file: {input_filename}\n")

    return input_filename

def write_pot_file(repeats: object, vectors: object) -> None:
    """Generates and writes out AIMPRO pot_file

    Args:
        repeats: number of repeats of each vector
        vectors: grid vectors

    Returns:
        None

    Raises:
        None
    """

    # Open an outfile in cwd
    # (N.B. this is the directory potfileGen was called from, not where it lives)
    outpath = Path.cwd() / cio.POT_OUTPUT_FILENAME

    if verbose_output:
        print(f"Writing output to file: {outpath}\n")

    num_grid_points = str(np.prod(repeats))

    # Open output file
    with open(outpath,"w") as outfile:

        # Write out number of grid points as line 1
        outfile.write(num_grid_points+"\n")

        if verbose_output:
            print(f"Writing {num_grid_points} grid points.\n")

        for ia in range(0, repeats[0]):
            for ib in range(0, repeats[1]):
                for ic in range(0, repeats[2]):

                    # Calculate grid point
                    grid_point = ia * vectors[0, :] \
                                    + ib * vectors[1, :] \
                                    + ic * vectors[2, :]

                    # Write grid point to file with 12.6f formatting
                    outfile.write("{gp_x:12.6f} {gp_y:12.6f} {gp_z:12.6f}\n"
                          .format(gp_x = grid_point[0],
                            gp_y = grid_point[1], gp_z = grid_point[2]))

        if verbose_output:
            print(f"Finished writing to: {outpath}\n")

def main() -> None:

    # Read cmd line for input file
    filename = read_commmand_line()

    # Get repeats and vectors from input file
    rep, vec = cio.read_grid_vectors(filename, verbose_output)

    # Write grid using vectors & their repeats
    write_pot_file(rep, vec)

if __name__ == "__main__":
    main()
