#!/usr/bin/env python3

# Copyright (c) A Christison 2025 All Rights Reserved.

"""pot_file generator: potfile_gen [options] grid_vectors_input_file

This script plots a regular grid in the required format for the potential job in the AIMPRO code that is valid for cubefile plotting.

AIMPRO potential job documentation
https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html

Cubefile format
https://www.quantum-espresso.org/Doc/INPUT_PP.html (&PLOT namelist, iflag = 3, output_format = 6)
https://paulbourke.net/dataformats/cube/

The output pot_file is written to the current working directory

[options]
-h, --help: display help dialogue
-v, --verbose: turn on verbose output mode, this prints useful status info to screen
-d, --debug: turn on debug mode (for developers only)

grid_vectors_input_file
Specifies the vectors & the number of their repeats defining the grid of points centred on each voxel of the parallelepiped plotting volume,
as well as the origin of the parallelepiped plotting volume, this can also be a filepath and/or bzip2 archive to/of the file.

The file is delimited by whitespace and has the format:

Origin_x(float)  Origin_y(float)  Origin_z(float)
Repeats_A(int)  A_x(float)  A_y(float)  A_z(float)
Repeats_B(int)  B_x(float)  B_y(float)  B_z(float)
Repeats_C(int)  C_x(float)  C_y(float)  C_z(float)

All vectors are in atomic units (i.e. Bohr).
Origin must be specified even if all values are zero.

Repeats values must be >= 1.
Vector components an have any valid float value.
Origin components can have any valid float value.

Floats are in 12.6 format.

It is often helpful to define grid with a reasonably dense sampling density within your system lattice.
This ensures that the potential is being sampled with high enough resolution and avoids spurious data points from sampling periodic images.

Unless a custom grid is required for a specific purpose, the FFT sampling grid density AIMPRO uses for a DFT calculation of your system is generally a suitable choice.

For the case of example_input.in, it is designed around a 1x1x1 simple cubic diamond system with a single lattice constant of 6.74 Bohr
and a sampling density of 36 data points in all dimensions of the unit cell, taken from the FFT grid density.
The grid vectors are aligned with the lattice vectors.

The calculation of grid vectors is as given:

(1.0 0.0 0.0) x 6.74/36 = (0.187222 0.000000 0.000000)
(0.0 1.0 0.0) x 6.74/36 = (0.000000 0.187222 0.000000)
(0.0 0.0 0.0) x 6.74/36 = (0.000000 0.000000 0.187222)

Sampling density therefor becomes the number of repeats, and by fixing the origin at (0.0 0.0 0.0) we obtain the contents of example_potfile_gen_input/example_input.in:

0.000000 0.000000 0.000000
36 0.187222 0.000000 0.000000
36 0.000000 0.187222 0.000000
36 0.000000 0.000000 0.187222

The general form of this calculation is given as:
(Lattice_vector_A) x Lattice_param_A / Sampling_density_in_A = (Grid_vector_A)
(Lattice_vector_B) x Lattice_param_B / Sampling_density_in_B = (Grid_vector_B)
(Lattice_vector_C) x Lattice_param_C / Sampling_density_in_C = (Grid_vector_C)

Where:

Sampling_density_in_A = Repeats_A
Sampling_density_in_B = Repeats_B
Sampling_density_in_C = Repeats_C

And Origin == System origin i.e. generally (0.0 0.0 0.0)

Known issues:
None
"""

# System modules
import argparse
from pathlib import Path
import sys
from typing import IO, Optional

# Third party modules
import numpy as np

# First party modules
import common_io as cio

# Module development info
VERSION_NUMBER = "0.4"
VERSION_DATE = "12/12/2025"
AUTHORS = "Alex Christison"
COPYRIGHT = "Copyright (c) A Christison 2025 All Rights Reserved"

def read_commmand_line() -> Optional[IO[str]]:
    """Gets input filename

    If no input file is provided in command line the default input file is used.

    Sets global verbose output flag if specified in cmd line args.

    Args:
        None

    Returns:
        input_filename: Filename of input file

    Raises:
        Errors & exits with message if incorrect number of args detected.
        Errors & exits with message if provided input file does not exist.
    """
    global verbose_output, debug

    parser = argparse.ArgumentParser(
                    prog = "potfile_gen",
                    formatter_class=argparse.RawDescriptionHelpFormatter,
                    description = "Plot a regular grid for the AIMPRO potential job. \
                                    \n\nAIMPRO potential job documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html",
                    epilog = f"Version info\n\nAuthor(s): {AUTHORS} \nVersion: {VERSION_NUMBER} \nDate: {VERSION_DATE} \n\n{COPYRIGHT}.") #pylint: disable=duplicate-code

    parser.add_argument("-v", "--verbose",                                                                  #pylint: disable=duplicate-code
                        action = "store_true",                                                              #pylint: disable=duplicate-code
                        help = "turn on verbose output mode, this prints useful status info to screen")     #pylint: disable=duplicate-code

    parser.add_argument("-d", "--debug",                                                                    #pylint: disable=duplicate-code
                        action = "store_true",                                                              #pylint: disable=duplicate-code
                        default = False,                                                                    #pylint: disable=duplicate-code
                        help = "turn on debug mode (for developers only)")                                  #pylint: disable=duplicate-code

    parser.add_argument("grid_vectors_input_file",
                        nargs = 1,
                        help = "grid vectors input file, this can also be a filepath and/or bzip2 archive to/of the file")

    args = parser.parse_args()
    verbose_output = args.verbose
    debug = args.debug
    input_filename = args.grid_vectors_input_file[0]

    # Disable traceback when not in debug mode
    if not debug:
        sys.tracebacklimit = 0

    # Check provided file is valid
    if not Path(input_filename).is_file():
        raise FileNotFoundError(f"no such file - '{input_filename}'")

    if verbose_output:
        print("Verbose output mode enabled\n")
        print(f"Input file: {input_filename}\n")

    return input_filename

def write_pot_file(grid_points: object, num_grid_points: int) -> None:
    """Generates and writes out AIMPRO pot_file

    Args:
        repeats: number of repeats of each vector
        vectors: grid vectors
        origin: parallelepiped grid origin

    Returns:
        None

    Raises:
        None
    """

    # Get output file path
    # (N.B. this is the directory potfile_gen was called from, not where it lives)
    outpath = Path.cwd() / cio.POT_OUTPUT_FILENAME

    if verbose_output:
        print(f"Writing output to file: {outpath}\n")

    np.savetxt(outpath, grid_points, fmt="%12.6f", header= str(num_grid_points), comments='')

    if verbose_output:
        print(f"Finished writing to: {outpath}")

def main() -> None:
    """Main method

    The main method is run when executing the prog.py file from console.

    This method is not designed to be called like a method from a module.
    """

    # Read cmd line for input file
    filename = read_commmand_line()

    # Get repeats and vectors from input file
    rep, vec, orig = cio.read_grid_vectors(filename, verbose_output)

    # Generate grid points
    g_pts, num_g_pts = cio.generate_grid_points(rep, vec, orig, verbose_output)

    # Write grid using vectors & their repeats
    write_pot_file(g_pts, num_g_pts)

if __name__ == "__main__":
    main()
