#!/usr/bin/env python3
"""Regular Grid Plotter: regGridPlot [options] [input_file]

This script plots a regular grid in the required format for the potential job in the AIMPRO code.

AIMPRO potential job documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html

The output pot_file is written to the current working directory

If no input file is specified the default input file in ./plot_input/default.in will be used. This file is user editable.

[options]
-d, --debug: Enables debug mode for verbose output.

[input_file]
Specifies the vectors & their repeats defining the grid.
The file is delimited by whitespace and has the format:

Repeats_A(int) A_x(float) A_y(float) A_z(float)
Repeats_B(int) B_x(float) B_y(float) B_z(float)
Repeats_C(int) C_x(float) C_y(float) C_z(float)

Integers are a maximum of 5 wide and floats are in 12.6 format.
"""

import argparse
import sys
from pathlib import Path, PurePath
import math
import os

#Module development info
VERSION = "0.1"
VERSION_DATE = "11/08/2025"
AUTHORS = "Alex Christison"

# Filename constants
DEFAULT_INPUT_FILENAME = os.path.dirname(__file__) +  "/plot_input/default.in" # Define filepath relative to script location
OUTPUT_FILENAME = "pot_file"

def read_commmand_line() -> str:
    """Gets input filename.

    If no input file is provided in command line the default input file is used.

    Args:
        None

    Returns:
        input_filename: Filename of input file

    Raises:
        Sets global verbose output flag if specified in cmd line args.
        Errors & exits with message if incorrect number of args detected.
    """
    global verbose_output

    parser = argparse.ArgumentParser(
                    prog="regGridPlot",
                    usage="regGridPlot [options] [input_file]",
                    description="Plot a regular grid for the AIMPRO potential job.",
                    epilog="AIMPRO potential job documentation: https://www.staff.ncl.ac.uk/j.p.goss/AIMPRO/restricted/docs/analysis/potential.html")

    parser.add_argument("-v", "--verbose",
                        action="store_true",
                        help="verbose output mode")

    parser.add_argument("input_file",
                        nargs="?",
                        default=DEFAULT_INPUT_FILENAME,
                        type=argparse.FileType("r"),
                        help="input file, if none specified default input file is used.")

    args = parser.parse_args()
    verbose_output = args.verbose

    # File was opened by argpass to check it exists, close and get name
    args.input_file.close()
    input_filename = args.input_file.name

    if verbose_output:
        print("Verbose output on\n")
        print(f"Input file: {input_filename}\n")

    return input_filename

def read_input_file(input_filename: str) -> list:
    """Reads input file.

    Args:
        input_filename: Input filename/path.

    Returns:
        repeats: number of repeats of each vector.
        vectors: grid vectors.

    Raises:
        Errors & exits with message if incorrect input file format detected.
    """

    # Define lists to store vectors & their repeats
    repeats = []
    vectors = []

    # Read in input file
    with open(input_filename,"r") as infile:
        # Split into rows
        raw_input = infile.read().splitlines()

    if len(raw_input) != 3:
        sys.exit(f"Error: incorrect input file format - {input_filename} must have only 3 rows")

    for row in raw_input:
        # Split in indvidual items
        split_row = row.split()

        if len(split_row) != 4:
            sys.exit(f"Error: incorrect input file format - {input_filename} must have only 4 columns")

        # Add data to lists
        repeats.append(int(split_row[0]))
        vectors.append([float(string) for string in split_row[1:4]])

    if verbose_output:
        print("Input data:\n")
        for i in range(len(repeats)):
            print("{rep:5d}, {vecx:12.6f}, {vecy:12.6f}, {vecz:12.6f}"
                  .format(rep = repeats[i],vecx = vectors[i][0],
                          vecy = vectors[i][1], vecz = vectors[i][2]))
        print("\n")

    return repeats, vectors

def write_pot_file(repeats: list, vectors: list) -> None:
    """Generates and writes out AIMPRO pot_file.

    Args:
        repeats: number of repeats of each vector.
        vectors: grid vectors.

    Returns:
        None

    Raises:
        None
    """

    # Open an outfile in cwd
    # (N.B. this is the directory regGridPlot.py was called from, not where it lives)
    outpath = Path.cwd() / OUTPUT_FILENAME

    if verbose_output:
        print(f"Writing output to file at: {outpath}\n")

    # Open output file
    with open(outpath,"w") as outfile:

        # Write out number of grid points as line 1
        outfile.write(str(math.prod(repeats)))

def main() -> None:

    # Read cmd line for input file
    filename = read_commmand_line()

    # Get repeats and vectors from input fike
    rep, vec = read_input_file(filename)

    # Write grid using vectors & their repeats
    write_pot_file(rep, vec)

if __name__ == "__main__":
    main()
