#!/usr/bin/perl -w

# Copyright (c) J.P. Goss 2015 All Rights Reserved.

#Optimistically assume adherence to "dat.xxx" file name convention:
if($#ARGV-1){die "wrong usage of InsertOTB\n"}
if($ARGV[0]=~/^dat/){
    $datfile=$ARGV[0];$otbfile=$ARGV[1];
}else{
    $datfile=$ARGV[1];$otbfile=$ARGV[0];
}
#Read in the otb:
open OTB, "<$otbfile" or die;while(<OTB>){$o.=$_}close(OTB);
#Read in the data file:
open DAT, "<$datfile" or die;
$keep=1;
while(<DAT>){
    if(/^\s*%/){}
    elsif(/begin.*\{positions\}/){$dat.=$_;$keep=0}
    elsif(/end\{positions\}/){$dat.=$o;$keep=1}
    if($keep){$dat.=$_}
}
close(DAT);
print $dat;
