#!/usr/bin/perl
use Math::Trig;
require 5;

# Copyright (c) J.P. Goss 2024 All Rights Reserved.

#Always start with the defaults:
&Defaults;

#The following line should be commented out to suppress immediate
#debugging output...
#$option{$invocation}{'debug'}[0]++;

#Get the command line options:
&SetSwitches;
&ProcessSwitches;

#Special cases:
if($invocation eq "o2x"||$options{$invocation}{'o2x'}[0]){&o2x($files[0]);&Exit()}
elsif($invocation eq "x2o"||$options{$invocation}{'x2o'}[0]){&x2o($files[0]);&Exit()}
elsif($options{$invocation}{'scale'}[0]){&scale($files[0],1);&Exit()}
elsif($options{$invocation}{'iscale'}[0]){&scale($files[0],-1);&Exit()}
elsif($invocation eq "analysis"||$options{$invocation}{'anal'}[0]){&anal($files[0]);&Exit()}
elsif($invocation eq "Homer"){&Homer($files[0]);&Exit()}
elsif($invocation eq "gres"){
    
    # Have we been asked to do something other than analyse dat/res files?
    if($options{$invocation}{'c'}[0]){&CleanUpDirectory;&Exit}
    
    #If we're accumulating Homer data...
    if($options{$invocation}{"allhomer"}[0]){$allhomerdata=OpenOutput(ALLHOMER,"force new","all",($options{$invocation}{'average'}[0]?"k-av":""),"accumulated homer input file")}
    
    
    # Then for each file, get the appropriate information:
    for $file (@files){
	
	&Initialise();
	
	# Try to determine the type of file we're looking at (eg AIMPRO output, xyz, otb, etc)
	if(&FileType($file) eq "otb"){
	    OpenInput($file);
	    while(<RES>){if($.==1&&/\%\s*(.*)$/){$data{"Species"}=$1}elsif(/^\s*\d+\s+(\d+)\s/){push @tmp,$1}}
	    $n=(sort bynumber @tmp)[$#tmp];
	    close(RES);
	    while((split" ",$data{"Species"})<$n){$data{"Species"}.=" X"}
	    OpenInput($file);
	    &GetOTB();
	    if($options{$invocation}{'bond'}[0]){&PrintBondCentreOTBFile()}
	}elsif(&FileType($file) eq "xyz"){
	    if($options{$invocation}{'bond'}[0]){}
	}elsif(&FileType($file) eq"aimpro"){
	    
	    #'GRES' results file:
	    &Gres($file);
	    
	    #If necessary, massage the data:
	    if(!$data{"Num. atoms"}){$data{"Num. atoms"}=$#{$data{'otb'}[1]}+1}
	    
	    #Convert lattice definitions into lattice vectors:
	    if(exists $data{"lattice type"}){
		if(exists $data{'d-latt P'}){
		    @{ $data{'d-latt P recon'} }= 
			LatticeDefinitions(
			    $data{"lattice type"},
			    $data{"lattice orient"},
			    $data{"lattice scale"},
			    (split" ",$data{"lattice params"})
			);
		    my $a=$b=$dp=0;
		    for(0..8){
			$a+=(${$data{'d-latt P'} }[$_]*${$data{'d-latt P'} }[$_]);
			$b+=(${$data{'d-latt P recon'} }[$_]*${$data{'d-latt P recon'} }[$_]);
			$dp+=(${$data{'d-latt P'} }[$_]*${$data{'d-latt P recon'} }[$_]);
		    }
		    $dp/=(sqrt($a)*sqrt($b));
		    if((1-$dp)>1e-5){
			printf "Internal check on lattice vectors has failed!\n a^2 = %10.5f, b^2 = %10.5f\n",$a, $b;
			printf "Dot product = %10.ef\n";$dp;
			printf "'d-latt P recon' (%d): \n%8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f \n",1*@{$data{'d-latt P recon'}},@{$data{'d-latt P recon'}};
			printf "      'd-latt P' (%d): \n%8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f \n",1*@{$data{'d-latt P'}},@{$data{'d-latt P'}};
			die;
			}
		}elsif(exists $data{"lattice type"}){
		    @{ $data{'d-latt P'} }= 
			LatticeDefinitions(
			    $data{"lattice type"},
			    $data{"lattice orient"},
			    $data{"lattice scale"},
			    (split" ",$data{"lattice params"})
			);
		    @{ $data{'d-latt C'} }= @{ $data{'d-latt P'} }[9..17];
		    @{ $data{'d-latt P'} }= @{ $data{'d-latt P'} }[0..8];
		}
	    }elsif(exists $data{"lattice vecs"}){
		@{ $data{"d-latt P"} }=(split" ",$data{"lattice vecs"});
		my $a=(split" ",$data{"lattice params"})[0];
		for(0..8){${$data{"d-latt P"}}[$_]*=$a}
	    }
	    
	    # Having got the information from the results file, output the
	    # information as requested
	    &Output();
	    
	}
	
	# Ensure that all the file handles are closed:
	&CloseAllFiles();
    }
    
    #If we need to, end the accummulation of homer data:
    if($options{$invocation}{'allhomer'}[0]){
	&PrintHOMERFile("allhomerend");
	&CloseAllFiles();
    }
}else{
    # If I get here then I've done something wrong...
    print "Apparently I know about '$invocation', but I don't know what to do next...\n";
    Exit();
}

# Run any system commands that result:
&System();

&Exit();

######################################################################
#### Subroutines #####################################################
######################################################################

######################################################################
#### Determine the most likely file type #############################
######################################################################
sub FileType{
    if($#_){die "Wrong number of arguments passed to File Type"}
    my $f=pop @_;
    OpenInput($f);
    my $filetype="aimpro";
    while(<RES>){
	next if /[\%\#]/;
	#If the file starts with a line containing a single integer it's probably an XYZ file:
	if(/^\s*\d+\s*$/){$filetype="xyz";last}
	#Does the line conform to OTB?
	elsif(/^\s*\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+-?(\d+\.?\d*|\.\d+)\s+-?(\d+\.?\d*|\.\d+)\s+-?(\d+\.?\d*|\.\d+)\s*$/){$filetype="otb";last}
	else{last}
    }
    close(RES);
    return $filetype;
}

######################################################################
#### System calls are made from the system hash ######################
######################################################################
sub System{
    my $spawn="";my $len=0;
    if(@{$system{'xyz'}}&&($options{$invocation}{'xyz'}[0] ne "NONE")){
	if($options{$invocation}{'xyz'}[0]=~/jmol/){
	    if($options{$invocation}{'q'}>1){$spawn.="\tSpawning XYZ viewer\n"}
	    for(@{$system{'xyz'}}){
		system "$options{$invocation}{'xyz'}[0] $_ &";
	    }
	}else{
	    my $files = (join" ",@{$system{'xyz'}});
	    if($options{$invocation}{'q'}>1){$spawn.="\tSpawning XYZ viewer\n"}
	    system "$options{$invocation}{'xyz'}[0] $files &";
	}
    }elsif(@{$system{'xyz'}}&&$options{$invocation}{'xyz'}[0] eq "NONE"){
	print "\a\t*** No XYZ displaying software detected ***\n";
    }
    if($options{$invocation}{'xhomer'}[0]&&($options{$invocation}{'postscript'}[0] ne "NONE")){
	foreach(@{$system{'postscript'}}){
	    system "$options{$invocation}{'postscript'}[0] $_ &";
	    $nviewers++;
	}
	if($options{$invocation}{'q'}>1){
	    $spawn.=("\tSpawning ".(($nviewers>1)?"$nviewers ":"")."PS viewer".(($nviewers>1)?"s":"")."\n");
	}
    }
    
    if($spawn){
        for(split"\n",$spawn){$len=(length($_)>$len)?length($_):$len}
        for(2..$len){$stars.="*"}
        print "\n\t$stars\n$spawn\t$stars\n";
    }
}

######################################################################
#### Initialise for each file ########################################
######################################################################
sub Initialise{
    $FirstSet=$interval=$DipoleSet=0;
    undef %data;
    undef %homerdata;
    %data=(
	'screened exchange'=>0,
	'rescaled positions'=>1,
	'lattice a0'=>1.0,
	'lattice scale'=>"1 1 1",
	'Optimise'=>"No optimisation"
	);
    return;
}

######################################################################
#### Set up the defaults and data hashes #############################
######################################################################
sub Defaults{
    $error=0;
    #File roots that are recognised:
    %root=(
	'PDB'=>'pdb',
	'CELL'=>'cell',
	'SAD'=>'xyz.saddle',
	'CHA'=>'xyz.latest',
	'NEB'=>'latest',
	'ANL'=>'anl',
	'DAT'=>'dat',
	'DDS'=>'dds',
	'DIAGDD'=>'diagdd',
	'EXPONS' => 'exp',
	'ALLHOMER' => 'hom',
	'HOMER' => 'hom',
	'HOMERPS' => '',
	'OTB'=>'otb',
	'SCA'=>'',
	'REC'=>'ddrestart',
	'RPT'=>'rpt',
	'WFN'=>'wfn',
	'XBS'=>'xbs',
	'XRPT'=>'xyz.rpt',
	'XYZ'=>'xyz'
	);
    #Constants:
    %const=(
	'angtoau'  => 1.889726126,
	'autoang'  => 0.529177210544,
	'rateconst'=> 1063056.42795046,
	'version'  => "6.2o April 2025"
	);
    #Atomic species data:
    # - Each entry is [mass, coval rad, vdw rad]
    # - Mass is proton masses, lengths in Angstrom
    # - '0.00' entries mark unknown values
    %Atoms=(
	Ag => ['107', '1.34', '1.27'],
	Al => ['027', '1.18', '1.70'],
	Ar => ['040', '1.74', '1.91'],
	As => ['075', '1.21', '2.00'],
	At => ['210', '0.00', '0.00'],
	Au => ['197', '1.34', '1.37'],
	B  => ['011', '0.91', '2.08'],
	Ba => ['138', '0.00', '0.00'],
	Be => ['009', '0.00', '0.00'],
	Bi => ['209', '1.52', '2.00'],
	Br => ['079', '1.14', '1.95'],
	C  => ['012', '0.77', '1.65'],
	Ca => ['040', '1.74', '1.18'],
	Cd => ['114', '1.49', '1.49'],
	Ce => ['140', '1.76', '1.76'],
	Cl => ['035', '0.99', '1.80'],
	Co => ['059', '1.16', '0.88'],
	Cr => ['052', '1.18', '1.37'],
	Cs => ['133', '2.35', '1.84'],
	Cu => ['063', '1.17', '0.72'],
	Dy => ['164', '1.76', '1.76'],
	Er => ['166', '1.76', '1.76'],
	Eu => ['153', '1.76', '1.76'],
	F  => ['019', '0.72', '1.40'],
	Fe => ['056', '1.17', '0.90'],
	Ga => ['069', '1.26', '1.37'],
	Gd => ['158', '1.76', '1.76'],
	Ge => ['074', '1.23', '1.25'],
	H  => ['001', '0.32', '1.25'],
	He => ['004', '0.31', '1.20'],
	Hf => ['180', '0.00', '0.00'],
	Hg => ['202', '1.44', '1.55'],
	Ho => ['165', '1.76', '1.76'],
	I  => ['127', '1.33', '2.15'],
	In => ['115', '1.63', '1.63'],
	Ir => ['193', '0.00', '0.00'],
	K  => ['039', '2.03', '1.44'],
	Kr => ['084', '0.00', '0.00'],
	La => ['139', '1.76', '1.76'],
	Li => ['007', '1.23', '1.86'],
	Lu => ['175', '0.00', '0.00'],
	Mg => ['024', '1.36', '0.87'],
	Mn => ['055', '1.17', '1.37'],
	Mo => ['098', '2.00', '2.00'],
	N  => ['014', '0.75', '1.50'],
	Na => ['023', '1.54', '1.12'],
	Nb => ['093', '0.00', '0.00'],
	Nd => ['142', '1.76', '1.76'],
	Ne => ['020', '1.31', '1.60'],
	Ni => ['058', '1.15', '0.69'],
	O  => ['016', '0.73', '1.35'],
	Os => ['192', '0.00', '0.00'],
	P  => ['031', '1.06', '1.75'],
	Pb => ['208', '2.15', '2.02'],
	Pd => ['106', '1.28', '1.63'],
	Pm => ['145', '1.76', '1.76'],
	Po => ['210', '0.00', '0.00'],
	Pr => ['141', '1.76', '1.76'],
	Pt => ['195', '1.38', '1.38'],
	Rb => ['085', '2.16', '1.58'],
	Re => ['187', '0.00', '0.00'],
	Rn => ['222', '0.00', '0.00'],
	Ru => ['102', '0.00', '0.00'],
	S  => ['032', '1.02', '1.85'],
	Sb => ['121', '1.82', '1.82'],
	Sc => ['045', '1.44', '1.37'],
	Se => ['080', '1.17', '2.00'],
	Si => ['028', '1.16', '1.93'],
	Sm => ['152', '1.76', '1.76'],
	Sn => ['120', '1.40', '2.17'],
	Sr => ['088', '0.00', '0.00'],
	Ta => ['181', '0.00', '0.00'],
	Tb => ['159', '1.76', '1.76'],
	Tc => ['099', '0.00', '0.00'],
	Te => ['130', '1.37', '2.20'],
	Th => ['103', '0.00', '0.00'],
	Ti => ['048', '1.32', '1.37'],
	Tl => ['205', '0.00', '0.00'],
	Tm => ['169', '1.76', '1.76'],
	V  => ['051', '1.22', '1.37'],
	W  => ['184', '1.30', '2.00'],
	Xe => ['129', '0.00', '0.00'],
	Y  => ['089', '0.00', '0.00'],
	Yb => ['174', '1.76', '1.76'],
	Zn => ['064', '1.25', '0.74'],
	Zr => ['090', '1.45', '2.00'],
	);
    #Set up a structure for the various options appropriate to
    #each invocation.  Implicit within are the default values.
    %options=(
	gres => {
	    "USAGE"     => [-1,  "bin", "gres <options> <files>",                                         1],
	    "allhomer"  => [0,   "bin", "Generate  single homer input for multiple res files",            1],
	    "anal"      => [0,   "bin", "Analysis of neighbour map for single otb file",                  1],
	    "average"   => [0,   "bin", "Output homer file with average over k-points",                   1],
	    "b"         => [0,   "bin", "Band file output with homer option",                             0],
	    "bond"      => [0,   "bin", "Generate otb with bond-centres as atoms (works on OTB input)",   1],
	    "bondfudge" => [2.0, "va1", "Multiplicitive factor for xbs bonds (default=2)",                1],
	    "c"         => [0,   "bin", "Clean up the current directory - rm xyz, otb, etc files",        1],
	    "centre"    => [0,   "bin", "When repeating unit cell, repeat in both directions",            1],
	    "d"         => [0,   "bin", "Get the double derivative matrix",                               1],
	    "D"         => [0,   "bin", "Get the eigenvalues and dipole matrix elements",                 0],
	    "debug"     => [0,   "bin", "Debugging output switched on",                                   1],
	    "diagdd"    => [0,   "bin", "Generate input file for diagdd",                                 1],
	    "e"         => [0,   "bin", "Get atomic positions for xyz animations",                        1],
	    "einit"     => [0,   "bin", "Get initial xyz structure",                                      1],
	    "elast"     => [0,   "bin", "Get final xyz structure",                                        1],
	    "xsaddle"   => [0,   "bin", "Get and open an xyz animation of saddle point NEB optimisation", 1],
	    "xlatest"   => [0,   "bin", "Get and open an xyz animation of latest NEB chain (latest.xyz)", 1],
	    "esaddle"   => [0,   "bin", "Get xyz animation of the NEB saddle point optimisation",         1],
	    "elatest"   => [0,   "bin", "Get xyz animation of the NEB latest chain (latest.xyz)",         1],
	    "erepeat"   => [0,   "va3", "Repeat a unit cell (xyz) in each lattice direction (3 integers)",1],
	    "erepeatlast"=> [0,   "va3", "Repeat unit cell (xyz) in lattice drctns (3 integers), last structure",      1],
	    "expons"    => [0,   "bin", "Get sorted list from exponent optimisation",                     1],
	    "h"         => [0,   "bin", "Help information",                                               1],
	    "homer"     => [0,   "bin", "Generate input file to be read into Homer(tm)",                  1],
	    "homerps"   => [0,   "bin", "Generate Homer input file and PS via Homer(tm)",                 1],
	    "homo"      => [0,   "bin", "Detect and output the homo (and lumo) evals",                    0],
	    "include"   => [0,   "va1", "Output the first \# atoms of the final positions in xbs format", 1],
	    "iscale"    => [0,   "va1", "Scale a single otb file by 1/this factor",                       1],
	    "n"         => [1.0, "va1", "Refractive index (C: 2.36, Si:3.46)",                            0],
	    "o"         => [0,   "bin", "Get atomic positions in `OTB' format (-v -> 1st & last iters)",  1],
	    "o2x"       => [0,   "bin", "o2x emulation -- may be used in conjunction with -s",            1],
	    "oinit"     => [0,   "bin", "Output initial iteration OTB",                                   1],
	    "olast"     => [0,   "bin", "Output final iteration OTB",                                     1],
	    "over"      => [0,   "bin", "Override file preservation",                                     1],
	    "q"         => [2,   "va1", "Quiet level \# (0-4) (larger numbers provide more output)",      1],
	    "r"         => [0,   "bin", "Evaluate rates for dipole transitions",                          0],
	    "repeat"    => [0,   "va3", "Repeat a unit cell (otb) in each lattice direction (3 integers) (use -anal subsequently for neighbour map)",1],
	    "R"         => [0,   "bin", "Reconstruct data file from results file",                        1],
	    "Rlast"     => [0,   "bin", "Reconstruct data file from results file - use last otb",         1],
	    "NEB"       => [0,   "bin", "Reconstruct latest.neb file from results file",                  1],
	    "radfudge"  => [0.5, "va1", "Multiplicitive factor for xbs atom radii (default=0.5)",         1],
	    "s"         => [0,   "va1", "Species for o2x emulation",                                      1],
	    "sort"      => [0,   "bin", "Sort expons data by energy",                                     1],
	    "scale"     => [0,   "va1", "Scale a single otb file by this factor",                         1],
	    "v"         => [0,   "bin", "Verbose output",                                                 1],
	    "V"         => [0,   "bin", "Version info",                                                   1],
	    "wf"        => [0,   "bin", "Get wavefunction coefficients",                                  1],
	    "wo"        => ['',  "va1", "Working directory for all output files",                         1],
	    "x"         => [0,   "bin", "Generate xyz animation and open in viewer",                      1],
	    "pdb"       => [0,,  "bin", "Generate pdb structure",                                         1],
	    "cell"      => [0,,  "bin", "Generate a .cell structure",                                     1],
	    "x2o"       => [0,   "bin", "Generate otb from single xyz file",                              1],
	    "xyz"       => [0,   "va1", "Set xyz viewer command",                                         1],
	    "xbs"       => [0,   "bin", "Output final positions in xbs format",                           1],
	    "xhomer"    => [0,   "bin", "Generate Homer input file and PS via Homer(tm) and view",        1],
	    "xinit"     => [0,   "bin", "Generate xyz of initial structure and open in viewer",           1],
	    "xrepeat"   => [0,   "va3", "Repeat & open xyz repeated in each direction (3 integers)",      1],
	    "xrepeatlast"=> [0,   "va3", "Repeat & open xyz repeated in each direction (3 integers), final structure",      1],
	    "xlast"     => [0,   "bin", "Generate xyz of final structure and open in viewer",             1]
	},
	o2x => {
	    "USAGE"     => [-1,  "bin", "o2x <-s \"C Si ...\"> file.otb",                                 1],
	    "debug"     => [0,   "bin", "Debugging output switched on",                                   1],
	    "h"         => [0,   "bin", "Help information",                                               1],
	    "s"         => [0,   "va1", "Atomic species",                                                 1],
	    "over"      => [0,   "bin", "Overwrite existing files",                                       1]
	},
	x2o => {
	    "USAGE"     => [-1,  "bin", "x2o file.xyz",                                                   1],
	    "bondfudge" => [2.24, "va1", "Multiplicitive fudge factor for bond lengths (default=2.24)",   1],
	    "debug"     => [0,   "bin", "Debugging output switched on",                                   1],
	    "h"         => [0,   "bin", "Help information",                                               1],
	    "over"      => [0,   "bin", "Overwrite existing files",                                       1]
	},
	analysis => {
	    "USAGE"     => [-1,  "bin", "analysis file.otb",                                              1],
	    "debug"     => [0,   "bin", "Debugging output switched on",                                   1],
	    "h"         => [0,   "bin", "Help information",                                               1],
	    "over"      => [0,   "bin", "Overwrite existing files",                                       1],
	    "bondfudge" => [2.0, "va1", "Multiplicitive fudge factor for bond lengths (default=2)",       1],
	    "s"         => [0,   "va1", "Atomic species",                                                 1]
	},
	Homer => {
	    "USAGE"     => [-1,  "bin", "Homer <input.file>",                                             1],
	    "area"      => [0,   "va2","Graph plot area (default 12x20cm) excluding labels",              1],
	    "debug"     => [0,   "bin", "Debugging output switched on",                                   1],
	    "h"         => [0,   "bin", "Help information",                                               1],
	    "sym"       => [9,   "va1", "Symbol size in points (default=9pt)",                            1],
	    "paper"     => [0,   "va2", "Paper size (default a4=21x29.7cm)",                              1],
	    "w"         => [5,   "va1", "White space above and below levels (default = 5%)",              1],
	    "s"         => [5,   "va1", "White space between spectra (default = 5%)",                     1],
	    "l"         => [1,   "va1", "Linewidth (default = 1)",                                        1],
	    "d"         => [1,   "va1", "Decimal places (default = 1)",                                   1],
	    "rep"       => [0,   "bin", "Replicate av to plot up & down",                                 1],
	    "over"      => [0,   "bin", "Overwrite existing files",                                       1]
	}	      
	);
    
    #How have I been invoked?
    &Invocation;
    
    #Set XYZ & PS viewing software:
    &setXYZviewer;
    &setPSviewer;
    
}

######################################################################
#### Look for the available software for viewing xyz data ############
######################################################################
sub setXYZviewer{
    local(%progs);
    #Listed here are the known packages for visualisation, along with 
    #the options required for XYZ format input.  The index preceding
    #the program name indicates the order of preference should a platform
    #have more that one available option.
    %progs=(
	"5 minimol" =>" ",
	"2 xmakemol"=>" -f",
	"3 xmol"    =>" -readFormat xyz",
	"4 rasmol"  =>" -xyz",
	"1 jmol"    =>" "
	);
    #Assume the worst:
    $options{$invocation}{'xyz'}[0]="NONE";
    #Look for the program on the machine and return the complete 
    #command line:
    for(sort keys %progs){
	($p)=/^\d (.*)/;
	open T, "which $p|";
	if(($t)=($t=<T>)=~/^(\/.*)\n$/){
	    $options{$invocation}{'xyz'}[0]=$t.$progs{$_};
	    last;
	}
	close T;
    }
}

######################################################################
#### Look for the available software for viewing ps data #############
######################################################################
sub setPSviewer{
    local(%progs);
    #Listed here are the known packages for visualisation.
    #The index preceding
    #the program name indicates the order of preference should a platform
    #have more that one available option.
    %progs=(
	"5 gv" =>" ",
	"2 ghostview" =>" ",
	"3 ggv" =>" ",
	"4 evince" =>" ",
	"1 display" =>" ",
	"6 ghostscript" =>" "
	);
    #Assume the worst:
    $options{$invocation}{'postscript'}[0]="NONE";
    #Look for the program on the machine and return the complete 
    #command line:
    for(sort keys %progs){
	($p)=/^\d (.*)/;
	open T, "which $p|";
	if(($t)=($t=<T>)=~/^(\/.*)\n$/){
	    $options{$invocation}{'postscript'}[0]=$t.$progs{$_};
	    last;
	}
	close T;
    }
}

######################################################################
#### Check that the invocation is known ##############################
######################################################################
sub Invocation{
    $invocation="";
    for(keys %options){	$invocation = $_ if $0 =~ /(\/|^)$_$/ }
    ##############################################
    ############### QUICK HACK: ##################
    ##############################################
    if($0 =~ /(\/|^)new_gres/){$invocation="gres"}
    if($0 =~ /(\/|^)aimgres/){$invocation="gres"}
    if($0 =~ /(\/|^)rgres/){$invocation="gres"}
    ##############################################
    die "Don't know how to run '$0'\n" if !$invocation;
}

######################################################################
#### Set switches hash from command line options #####################
######################################################################
sub SetSwitches{
    print "!DBG! In SetSwitches\n" if $options{$invocation}{'debug'}[0];
    while($_=shift @ARGV){
	#Switches:
	if(($a)=$_=~/^-(.*)$/){
	    die "Unknown option -$a\n" if !CheckOption($a);
	    if($options{$invocation}{'debug'}[0]){print "!DBG! Option -$a accepted\n";}
	    die "Can't set option -$a\n" if !SetOption($a);
	    if($options{$invocation}{'debug'}[0]){print "!DBG! Option -$a set to $options{$invocation}{$a}[0]\n";}
	}	
	#Files:
	else{if(-e $_){push @files,$_;}else{die "No such file: '$_'\n";}}
    }
}

######################################################################
#### Process the switches for combinations and global effects ########
######################################################################
sub ProcessSwitches{
    # Globals:
    if($options{$invocation}{h}[0]){&Help;}
    
    if($invocation eq "gres"){
	if($options{$invocation}{V}[0]){print "Version $const{'version'}\n";&Exit}
	
	# Combinations have extra effects:
	if($options{$invocation}{o}[0]&&$options{$invocation}{v}[0]){
	    $options{$invocation}{oinit}[0]=$options{$invocation}{olast}[0]=1;
	}
	if($options{$invocation}{v}[0]){$options{$invocation}{q}[0]=4;}
	
	# Some options might not require any files:
	if($options{$invocation}{'c'}[0]){return;}
	
	# ...others only want a single xyz or otb file:
	if($options{$invocation}{'scale'}[0] or
	   $options{$invocation}{'o2x'}[0] or 
	   $options{$invocation}{'anal'}[0] or 
	   $options{$invocation}{'x2o'}[0]){
	    if($#files){die "The option chosen requires a single file.\n"}
	    return;
	}
	
	# Otherwise, are there any files?
	if(!($#files+1)){print "No files provided!\n";&Help}
    }elsif($invocation eq "o2x"){
	if(!($#files+1)){print "No files provided!\n";&Help}
	if($#files){&Help}
    }elsif($invocation eq "x2o"){
	if(!($#files+1)){print "No files provided!\n";&Help}
	if($#files){&Help}
    }elsif($invocation eq "analysis"){
	if(!($#files+1)){print "No files provided!\n";&Help}
	if($#files){&Help}
    }elsif($invocation eq "Homer"){
	if(!($#files+1)){print "No files provided!\n";&Help}
	if($#files){&Help}
    }
}

######################################################################
#### Help output from the options hash ###############################
######################################################################
sub Help{
    print "Version $const{'version'}\nUsage: $options{$invocation}{USAGE}[2]\n$invocation options:\n";
    $l=0;for(keys %{$options{$invocation}}){
	next if $_ eq "USAGE";	               #Ignore usage info
	next if !$options{$invocation}{$_}[3]; #Ignore unsupported options
	$l=(length($_)>$l)?length($_):$l;
    } 
    for(sort keys %{$options{$invocation}}){
	next if $_ eq "USAGE";	               #Ignore usage info
	next if !$options{$invocation}{$_}[3]; #Ignore unsupported options
	print" "x(1+$l-length()),"-$_ ... $options{$invocation}{$_}[2]\n";
    }
    &Exit;
}

######################################################################
#### Check options hash for the one we've just been handed ###########
######################################################################
sub CheckOption{
    local $option=$_[0];
    die "Too many arguments given to 'CheckOption'" if $#_;
    for(keys % { $options{$invocation} }){return 1 if $_ eq $option and $options{$invocation}{$_[0]}[3];}
    # Check for maintainance flag (0=unsupported, 1=supported)
    for(keys % { $options{$invocation} }){
	if ($_ eq $option and !$options{$invocation}{$_[0]}[3]){ die "$_: Option not supported :-)\n";}
    }
    return 0;
}

######################################################################
#### Toggle binary switch / set a variable switch ####################
######################################################################
sub SetOption{
    die "Too many arguments given to 'SetOption'" if $#_;
    # Toggle Binary switch:
    if($options{$invocation}{$_[0]}[1] eq "bin"){$options{$invocation}{$_[0]}[0]=($options{$invocation}{$_[0]}[0])?0:1;return 1;}
    # Try to set a variable:
    elsif($options{$invocation}{$_[0]}[1] =~/^va([1-9])$/){
	#nval is the number of values that follow the command line option:
	my $nval=$1;$options{$invocation}{$_[0]}[0]="";
	while($nval){
	    if($_ = shift @ARGV){
		die "Argument(s) missing for option -$_[0]?\n" if /^-/;
		$options{$invocation}{$_[0]}[0].=($_.($nval>1?",":""));
	    }elsif($_ eq "0"){
		$options{$invocation}{$_[0]}[0].=("0".($nval>1?",":""));
	    }else{
		die"Argument(s) missing for option -$_[0]\n";
	    }
	    
	    --$nval;
	}
	return 1;
    }else{
	die "\aERROR: Major failure in setting options\n";
    }
}

######################################################################
#### Grep information from results file ##############################
######################################################################
sub Gres{
    #I need the name of the file to gres:
    if($#_){die "Wrong number of arguments supplied to Gres ($#_!=0)\n";}
    my $f=$_[0];
    OpenInput($f);
    if($options{$invocation}{'debug'}[0]){print "!DBG! At last... GRES\n";}    
    while(<RES>){
	# Ignore comment lines:
	next if /^\s*[%\#!]/;
	# - Run subroutines first - they may have data at the end that is still needed:
	if(/\*   dat   \*/){$xxx=1;$_=<RES>;$_=<RES>;next}
	if(/^[\s\/]*begin\{symmetry\}/){push @ { $data{'Data File'}},$_;$data{'Symmetry'}="Symmetry turned on";&GetSymmetry}	
	if(/EVAL/){$data{"SX points"}=0}
	while(/(evals|eval|unoccupied|k-point|kpoint|min energy|max energy|avg energy)/){
	    if($options{$invocation}{'debug'}[0]){print "!DBG! EVALS: $_\n";}    
	    last if /Special|folded|reduced|dE_/;
	    last if /E_sx|E_i/;
	    last if /WAVEFUNCTION/;
	    last if /analysis\{/;
	    $data{"SX points"}++;
	    my $t=$1;
	    if(/spin, kpoint :\s+(\d+)\s+(\d+)/){
		$data{'Num. k-points'}=$2;
		if($data{'Metallic'}){$data{"mue $1"}=(split)[7]}
	    }
	    if(/spin, (min|max|avg)/){
		$t=$1;$data{"Compressed evals"}=1;
		if($data{'Metallic'}){
		    my$s=(split)[5];
		    if($data{'Metallic'}){$data{"mue $s"}=(split)[6]}
		}
	    }
	    last if /nominally/;
	    if($t!~/unocc/){$data{'EvalSet'}++;}
	    &GetEvals($t);	    
	}
	if(/(positions\}|positions of atoms|cluster\})/ and !/(end|charge|restart)/){
	    if(/units=/){$data{"rescaled positions"}=0}
	    if(/\[atomic\]/){$data{'units'}="Positions given in a.u.";$data{"unit definition"}="atomic";}
	    elsif(/\[ang/){$data{'units'}="Positions given in Angstrom";$data{"unit definition"}="ang";}
	    elsif(/\[int-p/){$data{'units'}="Positions given by internal (int-p)";$data{"unit definition"}="int-p"}
	    elsif(/\[int-c/){$data{'units'}="Positions given by internal (int-c)";$data{"unit definition"}="int-c"}
	    elsif(/\[internal/){$data{'units'}="Positions given by internal";$data{"unit definition"}="internal"}
	    elsif(/\[(.*)\]/){$data{'units'}="Positions given by a scaling factor ($1)";$data{"unit definition"}=$1}
	    elsif(/begin\{pos/i&&!$data{"unit definition"}){$data{'units'}="Initial positions given by a0";$data{"unit definition"}="relative"}
	    elsif(/begin\{clust/i&&!$data{"unit definition"}){$data{'units'}="Initial positions in a.u.";$data{"unit definition"}="atomic"}
	    if(/(begin)/){push @ { $data{'Data File'}},$_}
	    $data{'OTBSet'}++;
	    if($options{$invocation}{'debug'}[0]){chomp;print "!DBG! Incrementing OTBSet: line $. ($data{'OTBSet'}), '$_'\n";}
	    &GetOTB();
	}
	if(/begin.*\{lattice\}/){push @ { $data{'Data File'}},$_;&GetLattice}
	while(/wavefunction coef/){$data{'WFNcoef'}++;&GetWFN}
	while(/DIPOLE/){$data{'DipoleSet'}++;&GetDipole}
	if(/use_kpar/){$data{use_kpar}=1}
	if(/row of dynamical matrix/){&GetDDS}
	if(/parameter\{.*exc\s*=\s*([a-z]+)\s*[\s,\}]/){$data{EXC}=$1}
	if(/parameter\{.*use_real_space_build.*\}/){$data{RSB}=1}
	if(/parameter\{.*gvec_cutoff\s*=\s*(.*)?\}/){$data{gvec_cutoff}=$1}
	if(/begin\{(bhs|pseudo|hghpseudo)\}/){
	    push @ { $data{'Data File'}},$_;
	    if($1 eq "bhs"){
		$data{'Basis type'}="Analytical";
	    }elsif($1 eq "pseudo"){
		$data{'Basis type'}="Tabulated";
	    }elsif($1 eq "hghpseudo"){
		$data{'Basis type'}="HGH";
	    }
	    &GetSpecies;
	}
	if(/2DD TO BE CALCULATED/){&Get2DD}
	if(/begin.*sampling/){push @ { $data{'Data File'}},$_;&GetSampling}
	if(/The following bond centres have been identified/){&GetBondCentrePositions(0)}
	if(/the following bond centres have been included/){&GetBondCentrePositions(1)}	
	##########################################
	# Now for the easier to get information: #
	##########################################
	chomp;
	# - Restart Dump information
	if(/DONE READING OF RESTART DUMP  (?)/){$data{'restart read'}=$1}
	if(/WRITTEN RESTART DUMP/){$data{'restart write'}++}
	# - TAGE screened exchange
	if(/Here comes screended EXCHANGE/){$data{"screened exchange"}=1;next}
	# - The starting banner (some versions)
	if(/ABINITIO/){$data{"starting banner"}++;next}
	# - Reproduction of data file:
	if(/^\s*(\/.*)/||$xxx){push @ { $data{'Data File'}},$_;}  #No next here!!!
	if(/end\{data\}/){$xxx=0}
	# - Symmetry: 
	if(/\s*Isogonal point group: (\w+) /){$data{'Group'}="(".$1.")";next}	
	if(/\s*MATRICES :\s*(\d+)/){$data{'Symmetry'}="$1 symmetry operation".($1-1?"s":"")." detected".($data{'Group'}?" $data{'Group'}":"").".";next}	
	if(/symmetry of molecule identified as (\S+)/||/symmetry identified as (\S+)/){$data{'Symmetry'}="Molecular symmetry set to '$1'.";next}
	if(/spherical top|symmetric top/){$data{'Symmetry'}="\aSYMMETRIC TOP";next}
	# - Complete output?
	if(/time : end\s+\d+\s+(\S+)\s/){$data{'Completed'}="Apparently ($1s)";next}
	# - Self-consistency and total energy:
	if(/not converged/){$data{'not converged'}.=(($data{'Num. iteration'}?$data{'Num. iteration'}:0)." ");next}
	if(/mcmax\s+(\d+)/){$data{'mcmax'}=$1;delete $data{'Final energy mc,'};next}
	if(/point ([12]) /){$data{'point data'}=$1;next}
	if(/mc,/||/etot,echerr/){
	    print "!DBG! ETOT located ($_)\n" if $options{$invocation}{'debug'}[0];
	    if(exists $data{'Final energy egy'}&&!$data{'point data'}){delete $data{'Final energy egy'}}
	    $data{'Final energy mc,'}=(split)[2];
	    $data{"echerr $data{'point data'}"}=(split)[3];
	    next;
	}
	if(/egy /){
	    if($data{'mcmax'}){delete $data{'mcmax'}}
	    @{$data{'Energy components'}}=(split);
	    $data{'Final energy egy'}=$data{'Energy components'}[1];
	    delete $data{'Final energy mc,'};
	    next;
	}
	if(/etot/){@{$data{'Energy terms'}}=(split",",$_);next}
	if(/ SHIFTT\(ch\/neut\):(.*)$/){$data{'Energy shiftt'}=$1;$data{'Energy shiftt'}=~s/,//g;}
	if(/ To get backward compatible energy, add: (.*)$/){$data{"backward"}++;$data{"Energy shiftt"}="0 $1";}
	if(/ To get backward compatible energy, subtract: (.*)$/){$data{"backward"}++;$data{"Energy shiftt"}="$1 0";}
	# - Optimisation	
	if(/atoms to be optimised :(.*)$/){$data{'Optimise'}=eval($1)." atoms optimised";next}
	if(/^\s*latconst/){$data{'Optimise'}="Isotropic lattice constant optimisation";next}
	if(/all atoms to be optimised/){$data{'Optimise'}="All atoms optimised";next}
	if(/atoms to be optimised :\s+(\d+)/){my $o;$_="";while(($_=<RES>)=~/^\s*\d+/){$o.=$_};@{$data{'Optimised atoms'}}=split " ",$o;next}
	if(/optimise\{(.*)\}/){my$o=$1;if($o=~/all/){$data{'Optimise'}="All atoms optimised"}else{@{$data{'Optimised atoms'}}=split " ",$o};next}
	if(/iteration :/){$data{'Num. iteration'}++;delete $data{'point data'};next}
	if(/final energy.*\s(\S+)$/){
	    $data{'Final energy'}=$1;
	    delete $data{'Final energy egy'};
	    next;
	}
	if(/final gradient.*\s(\S+)$/){$data{'Final gradient'}=$1;next}
	if(/maximum move\s*(\S+)$/){$data{'Maximum move'}=$1;next}
	if(/maximum at move \(au\)\s*(\S+)$/){$data{'Maximum move'}=$1;next}
	if(/maximum lv move \(au\)\s*(\S+)$/){$data{'Maximum lv move'}=$1;next}
	if(/maximum force.*\s(\S+)$/){$data{'Maximum force'}=$1;next}
	if(/energy change.*\s(\S+)$/){$data{'Energy change'}=eval($1);next}
	if(/relative energy.*\s(\S+)$/){$a=$1;$a=~s/D/e/;$data{'Relative energy'}=eval($a);next}
	if(/( diffusion point |DIF POINT)/){push @{$data{'DiffPoint'}},$data{'OTBSet'};next}
	if(/^[abc]ucl:(.*)$/){
	    my $i=$data{'OTBSet'}+1;
	    push @{$data{"d-latt P $i"}},(split" ",$1);next;
	}
	if(/^pars:(.*)$/){
	    push @{$data{'pars'}[$data{'OTBSet'}]},(split" ",$1);next;
	}	
	# - NEB runs
	if(/Nudged Elastic Band Diffusion Run/){$data{'NEB'}=1;next}
	if(/Number of Images\s+=\s*(\d+)$/){$data{'NEB nimages'}=$1;next}
	if(/Number of Passes\s+=\s*(\d+)$/){$data{'NEB passes'}=$1;next}
	if(/Structural Iters per pass.+=\s*(\d+)$/){$data{'NEB nopt'}=$1;next}
	if(/Path specification\s+=\s([0-9a-z\-]+)\s*$/){$data{'NEB path'}=$1;next}
	if(/Climbing band after iter\s+=\s*(-?\d+)$/){$data{'NEB climb'}=$1;next}
	# - Exponent optimisation
	if(/optexp\{(.*)\}/){$data{'optexp'}=$1;next}
	if(/ABC\s+\d+\s+(.*)$/){push @ { $data{'ABC'} },$1;next}
	# - Number of atoms/types:
	if(/no. atoms=\s+(\d+)\s+no. types=\s+(\d+)/){$data{'Num. atoms'}=$1;$data{'Num. types'}=$2;next}
	if(/natom\s+:\s+(\d+)/){$data{'Num. atoms'}=$1;next}
	if(/nty\s+:\s+(\d+)/){$data{'Num. types'}=$1;next}
	# - Electronic levels:
	if(/nkpt\s+:\s+(\d+)/){$data{'Num. k-points'}=$1;next}
	if(/Processing filling of one-electron states/&&!$data{'Num. k-points'}){$data{'Num. k-points'}=$#{$data{'k-points'}}+1}
	if(/Filling chosen :\s+(\S+.*)/){$data{"Electronic levels (".++$data{"Spin"}.")"}.=join " ",split " ",$1;next}
	if(/spin, nfild,npfil,wtpoc :\s+(\d)\s+(\S+.*)/){$data{"Electronic levels ($1)"}.=join " ",split " ",$2;$data{"Spin"}=$1;next}
	if(/filling.*metallic/){$data{'Metallic'}=1}
	if(/filling.*unpaired\s*=\s*\?/){$data{'autospin'}=1}
	if(/filling.*smear=([a-z]*)?[ ,}]/){$data{'Smearing'}=$1}
	if(/kt=\s*([\d\.]*)/i){$data{'Temperature'}=$1;next}
	if(/Zero temp/i){$data{'Temperature'}=0;next}
	if(/finite temperature calculation, beta=\s*(\S*)$/ or /Finite temperature, kT is :\s*(\S+)$/){$data{'Temperature'}=eval($1);next}
	if(/k point\s+[\d\*]+\s+(\S.*)$/){push @ { $data{'k-points'} },$1;next}
	if(/of electrons :\s*(\d+)/){$data{'Num. electrons'}=$1;next}
	if(/NET MAGNETIC MOMENT\s+(-?\d.+) /){$data{'muB'}=$1;next}
	if(/fix_kpt_occ=FALSE/){$data{'Metallic'}=1;next}
	# - Evals are stored in the 'data' hash in arrays called 'evals'
	if(/proton charge=\s*(\S+)$/||/Charged Unit cell.*\s(\S+)$/){$data{'Charge state'}=eval($1);next}
	# - Atom positions
	if(/unit\{atomic\}/){$data{'units'}="Positions given in a.u.";$data{"unit definition"}="atomic";next}
	if(/unit\{ang.*\}/){$data{'units'}="Positions given in Angstrom.";$data{"unit definition"}="angstroms";next}
	if(/lattice\{(.*)\}/){
	    $c=$1;
	    $c=~s/,\s+/,/g;
	    $c=~s/\s+=/=/g;
	    my$a;for$a(split ",",$c){my @d=split"=",$a;if($d[0] eq "iorient"){$d[0]="orient"}$data{"lattice $d[0]"}=$d[1]}
	    if(!$data{"lattice params"}){$data{"lattice params"}=$data{"lattice a0"}}
	    if(!$data{"lattice orient"}){$data{"lattice orient"}=1}
	}
	# - Mulliken stuff and wavefunction coefficients
	if(/mulliken populations to be found between levels(.*)and(.*)$/){$data{'Mulliken analysis'}=eval($1)." -> ".eval($2);next}
	# - Energy Double Derivs
	if(/derivs.*\{(.*)\}/){@ { $data{"dds"} } = (split " ",$1);next}
	if(/ atoms for which derivatives are to be found :(.*)$/){$data{"N dds"}=$1;next}
	if(/ derivatives to be found for all atoms/){$data{"N dds"}=$data{'Num. atoms'};next}
	if(/REC/){$data{'REC'}.=($_."\n");next}
	# - Restart options:
	if(/restart\{(.*)\}/){
	    for (split ",",$1){
		s/\s//g;
		if(/^(.*)=(.*)$/){$data{"restart options $1"}=$2;}else{$data{"restart options $_"}=1}
	    }
	    next;
	}
	# - Basis
	if(/chden\{\s*(\d+)\s*\}/){$data{'Charge Density option'}=$1;next;}
	if(/SIZES : (NDIM\/NSP\/NFIT\/NBTOT) :(.*)$/){@a=split"/",lc($1);@b=split" ",$2;for(0..3){$data{"Basis $a[$_]"}=$b[$_];}next}
	if(($a,$b)=/(nfit,ndim.*):(.*)$/){$a=~s/\s//g;@a=split",",lc($a);@b=split" ",$b;for(0..3){$data{"Basis $a[$_]"}=$b[$_];}next}
	if(/DFLT/){$data{'Basis BCs'}++;next}
	if(/energy cutoff :(.*)/){$data{"Ecut"}=eval($1);next}
	if(/size of fft grid :(.*)/){@ { $data{"FFT grid"}}=(split" ",$1);next}
	if(/Lattice constant \(au\)\s*(\S+)/){$data{"Optimised a0"}=$1;next}
	if(/\"Lattice constant\"\s*(\S+)/){$data{"Optimised a0"}=$1;next}
	if(/Minimum energy \(au\) is(.*)$/){$data{"Optimised energy"}=$1;next}
	if(/Bulk modulus \(au\)\s*(\S+)/){$data{"Bulk modulus au"}=$1;next}
	if(/Bulk modulus \(SI\)\s*(\S+)/){$data{"Bulk modulus SI"}=$1;next}
	if(/A PROBLEM WAS DETECTED IN DIAGONALISATION/){$data{"DIIS warning"}++;next}
	# Lattice definition given during output	
	if(/^\s*unit vectors/){&GetLatticeVectors("P")}
	if(/^\s* CC unit vectors/){&GetLatticeVectors("C")}
	# NEB data
	if(/\s\d+\s+ichain/){
	    &GetNEBimage(
			 (!exists $data{"NEB iter"}?0:$data{"NEB iter"}+1),
			 (split)[0]);
	}
	if(/s and d/){$data{"NEB iter"}=(split)[9];&GetNEBenergies()}
	if(/saddle/){$data{"NEB saddle image"}[$data{"NEB iter"}]=(split)[5];&GetNEBsaddle($data{"NEB iter"})}
    }
}

######     #    #       ######   ####
#          #    #       #       #
#####      #    #       #####    ####
#          #    #       #            #
#          #    #       #       #    #
#          #    ######  ######   ####

######################################################################
#### Open the results file ###########################################
######################################################################
sub OpenInput{
    #I need to be given the name of the file to open:
    if($#_){die "Wrong no. of arguments for openinput!\n";}
    my $file=$_[0];$tag="";
    my $compressed=0;
    if($options{$invocation}{'debug'}[0]){print "!DBG! Opening input file\n";}
    #Check the file name for subdirectories and split off res or rest
    if($file=~m+^(.*)/(.*)+){$dir="$1/";$file=$2;}else{$dir="./";}
    if($file=~/^(.*)(\.gz|\.bz2|\.Z)$/){$file=$1;$compressed=$2;}
    if($file=~/^rest?\.(.*)$/){$tag=$1;}else{$tag=$file;}
    if($options{$invocation}{'debug'}[0]){
	print "!DBG! '$dir', '$file', '$compressed'\n";
    }
    if($compressed){
	if($compressed eq ".bz2"){
	    # Check that the compression method exists:
	    my $a=`which bzip2`;if($a=~/bzip2 not in/i){die "Cannot bzip2!\n"}
	    open(RES,"bzip2 -cd $dir$file.bz2|") or die"cannot open $dir$file\n";
	}else{
	    my $a=`which gzip`;if($a=~/gzip not in/i){die "Cannot gzip!\n"}
	    open(RES,"gzip -cd $dir$file|") or die"cannot open $dir$file\n";
	}
    }else{
	open(RES,"$dir$file") or die "cannot open $dir$file\n";
    }
    # Record the fact that the file has been opened
    @ { $OpenFiles{RES} } = ("$file","");
}

######################################################################
#### File rename to not overwrite ####################################
######################################################################
sub OpenOutput{
    #
    # Arguments are it's type (HANDLE), anything to add to the end of
    # the filename, and a description of the contents.  The hash
    # %OpenFiles contains this information.
    #
    die "Wrong number of arguments passed to OpenOutput\n" if ($#_-4);
    my ($h,$mode,$body,$t,$d)=@_;
    #The file type must be registered in the root hash:
    if(!exists $root{$h}){die "Error in OpenOutput: file type $h not defined in root hash\n";}
    $f="";
    #Test to see if one can write files where you are asking:
    my @destinations=("","$ENV{HOME}/scratch/","/tmp");
    if($options{$invocation}{'wo'}[0]){unshift @destinations,$options{$invocation}{'wo'}[0]}
    while(@destinations){
	$a=shift @destinations;
	if($a eq ""){$a="."}
	if(-w "$a"){last}
	# We've looked at the possibilities and found nowhere to write:
	if($#destinations==-1){
	    print "\a\t***Cannot write to any of the suggested directories***\n";
	    return 0;
	}
    }
    if($a ne $options{$invocation}{'wo'}[0] and $options{$invocation}{'wo'}[0]){
	print "\t\a***Cannot write to $options{$invocation}{'wo'}[0]: defaulting to $a***\n";
    }
    if($a ne "." and !$options{$invocation}{'wo'}[0]){
	print "\t\a***Cannot write to current directory: defaulting to $a***\n";
    }
    if($a eq "."){$options{$invocation}{'wo'}[0]=""}else{$options{$invocation}{'wo'}[0]=$a}
    #Now build the file name including the path where needed:
    if($options{$invocation}{'wo'}[0]){$f=$options{$invocation}{'wo'}[0]."/";}
    if($root{$h}){$f.=$root{$h}.".$body".($t?".$t":"")}else{$f.="$body".($t?".$t":"")}
    print "!DBG! file: $f, tail: $t, handle: $h, description: $d\n" if $options{$invocation}{debug}[0];
    #
    #If the -over flag is used, then do not preserve any existing
    #files.
    #
    if(!$options{$invocation}{'over'}[0] 
       && $mode ne "force new"
       && $mode ne "append"
	){$f.="+"while(-e "$f");}
    #
    if($mode eq "new" || $mode eq "force new"){
	open $h,">$f" or die "can't open $h: $f\n";
    }elsif($mode eq "append"){
	open $h,">>$f" or die "can't open $h: $f\n";
    }
    chmod 0666, $f;
    select $h;$|=1;select STDOUT;
    # Put into record that this file has been opened:
    @ { $OpenFiles{$h} } = ($f,$d);
    return $f;
}

######################################################################
#### Close all open file handles (where appropriate?) ################
######################################################################
sub CloseAllFiles{while(($a,$b)=each %OpenFiles){close($a);delete $OpenFiles{$a}}}

######################################################################
#### Close all open file handles and exit for a clean getaway ########
######################################################################
sub Exit{
    &CloseAllFiles;
    if($ENV{HOSTNAME}=~/snufkin/){exit}
    if($ENV{HOSTNAME}=~/rhodes/){exit}
    if($ENV{HOSTNAME}=~/trueman/){exit}
    if($ENV{HOSTNAME}=~/polaris/){exit}
    if($ENV{HOSTNAME}=~/srif/){exit}
    if($ENV{HOSTNAME}=~/verity/){exit}
    #if($error){die "\n"}else{exit}
}

######################################################################
#### Convert xyz to otb format: ######################################
######################################################################
sub x2o{
    if($#_){die "Wrong no. of arguments passed to x2o\n";}
    my ($n,$file)=(0,$_[0]);
    my @r=();
    OpenInput($file);
    if(OpenOutput(OTB,"new",$tag,"","OTB output")){
	while(<RES>){
	    if($.==1){$natom=$_}
	    elsif($.==2){next}
	    else{
		@d=split;
		if($#d==3||$#d==4||$#d==6||$#d==7){
		    if(!exists $type{$d[0]}){$type{$d[0]}=++$ntype;$type2[$ntype]=$d[0]}
		    $species[++$n]=$d[0];
		    for(1..3){$d[$_]/=$const{'autoang'}}
		    push @{$r[$n]},@d[1..3];
		}else{
		    die "Error reading $file ($#d): is it really xyz?\n";
		}
	    }
	}
	# Check that the correct number has been read in:
	if($n-$natom){die "The XYZ and no. atoms read in does not agree\n";}
	# Now for the slow bit - what are the neighbours?
	# (Here we use the atomic radii of the two species multiplied by the
	# "bondfudge" factor.)
	# Work out the length-scale for the zoning of the structure...
	my $rmax=0;
	for my $i(1..$n){
	    my$t=$Atoms{$species[$i]}[1];
	    $rmax=($t>$rmax?$t:$rmax);
	}
	$rmax*=2*$options{$invocation}{'bondfudge'}[0];
        $rmax=($rmax?$rmax:1);
	
	# In practice, we compare squares of distances...
	my $r2max=$rmax*$rmax;
	
	my@address=();
	my@list=();
	# Allocate each atom to a zone...
	
	for $i (1..$n){
	    my @cell=();
	    for my $j (0..2){
		my $r=$r[$i][$j];
		$cell[$j]=($r>0?int($r/$rmax):int($r/$rmax-1));
	    }
	    @{$address[$i]}=@cell;
	    for my $c1 (-1,0,1){
		for my $c2 (-1,0,1){
		    for my $c3 (-1,0,1){
			push @{$list{$cell[0]+$c1}{$cell[1]+$c2}{$cell[2]+$c3}},$i
		    }
		}
	    }
	}
	
	# Now find the neighbours...
	for my $atom (1..$n){
	    my @list=@{$list{$address[$atom][0]}{$address[$atom][1]}{$address[$atom][2]}};
	    my $m=$#list;
	    my @r2=();
	    my %d2=();
	    for my $i (0..$m){
		next unless ($atom-$list[$i]); 
		for my $k (0..2){
		    $r2[$list[$i]]+=($r[$atom][$k]-$r[$list[$i]][$k])**2;
		}
		push @{$d2{$r2[$list[$i]]}},$list[$i];
	    }
	    my $r1=$Atoms{$species[$atom]}[1];
	    for my $j (sort bynumber keys %d2){		
		my $dist=sqrt($j);
		for my $k (sort bynumber @{$d2{$j}}){
		    my $r2=$Atoms{$species[$k]}[1];
		    my $test=$options{$invocation}{'bondfudge'}[0]
			*($r1+$r2);
		    if($test>=$dist){
			push @{$neighbours[$atom]},"$dist $k";
		    }
		}
	    }
	}
	print OTB "%".(join" ",@type2)."\n";
	for $i (1..$n){
	    #We need 4 neighbours:
	    my @tmp=();
	    my @n=(0,0,0,0);
	    for((BubbleSort(@{$neighbours[$i]}))[0..3]){push@tmp,(split)[1]}
	    @n=(@tmp,@n);
	    print OTB (FormatOTB(join" ",
				 $i,
				 $type{$species[$i]},
				 @n[0..3],
				 @{$r[$i]})
		);
	}
    }
    &FileSummary;
}

####   #    #   #####  #####   #    #   #####
#    #  #    #     #    #    #  #    #     #
#    #  #    #     #    #    #  #    #     #
#    #  #    #     #    #####   #    #     #
#    #  #    #     #    #       #    #     #
####    ####      #    #        ####      #

######################################################################
#### Output the data hash as far as required #########################
######################################################################
sub Output{
    if($options{$invocation}{'debug'}[0]){
	print "!DBG! Output data hash\n";
	for(sort keys %data){
	    print "$_:\t'$data{$_}'\n";
	}
    }
    #Summarise the contents of the file:
    if($options{$invocation}{'q'}[0]>0){
	&Summary;
    }
    
    # Output to separate files where appropriate:
    if($options{$invocation}{'bond'}[0]){&PrintBondCentreOTBFile();}
    if($options{$invocation}{'d'}[0]){&PrintDDSFile();}
    if($options{$invocation}{'diagdd'}[0]){&PrintDIAGDDFile();}
    if($options{$invocation}{'e'}[0]||$options{$invocation}{'x'}[0]){&PrintXYZFile(-1);}
    if($options{$invocation}{'pdb'}[0]){&PrintPDBFile($data{'OTBSet'});}
    if($options{$invocation}{'cell'}[0]){&PrintCELLFile($data{'OTBSet'});}
    if($options{$invocation}{'einit'}[0]||$options{$invocation}{'xinit'}[0]){&PrintXYZFile(1);}
    if($options{$invocation}{'elast'}[0]||$options{$invocation}{'xlast'}[0]){&PrintXYZFile($data{'OTBSet'});}
    if($options{$invocation}{'esaddle'}[0]||$options{$invocation}{'xsaddle'}[0]){&PrintNEBFile('saddle');}
    if($options{$invocation}{'elatest'}[0]||$options{$invocation}{'xlatest'}[0]){&PrintNEBFile('latest');}
    if($options{$invocation}{'expons'}[0]){&PrintEXPONSFile();}
    if($options{$invocation}{'allhomer'}[0]){&PrintHOMERFile("all");}
    if($options{$invocation}{'homer'}[0]||$options{$invocation}{'homerps'}[0]||$options{$invocation}{'xhomer'}[0]){$homerfile=&PrintHOMERFile("one");}
    if($options{$invocation}{'homerps'}[0]||$options{$invocation}{'xhomer'}[0]){&Homer($homerfile);}
    if($options{$invocation}{'o'}[0]){&PrintOTBFile(-1);}
    if($options{$invocation}{'oinit'}[0]){&PrintOTBFile(1);}
    if($options{$invocation}{'olast'}[0]){&PrintOTBFile($data{'OTBSet'});}
    if($options{$invocation}{'repeat'}[0]||$options{$invocation}{'xrepeat'}[0]||$options{$invocation}{'erepeatlast'}[0]||$options{$invocation}{'xrepeatlast'}[0]||$options{$invocation}{'erepeat'}[0]){@_=();&PrintREPEATFile;}
    if($options{$invocation}{'R'}[0]){&PrintDATFile(1);}
    if($options{$invocation}{'NEB'}[0]){&PrintLATESTNEB($data{"NEB iter"});}
    if($options{$invocation}{'Rlast'}[0]){&PrintDATFile($data{'OTBSet'});}
    if($options{$invocation}{'xbs'}[0]){&PrintXBSFile();}
    if($options{$invocation}{'wf'}[0]){&PrintWFNFile();}
    
    # End with a summary of the files produced...
    if((keys %OpenFiles)-1+(keys %FileComments)){&FileSummary();}
}

######################################################################
#### Output the pretty formatted info as required ####################
######################################################################

sub Summary{
    print "$file:\n";
    
    # Atomic info:
    if($options{$invocation}{'q'}[0]>3){print "\n\t**ATOMS**\n";}
    if(exists $data{'Species'}){print "\tAtomic types (",$data{'Species'}=~tr/ / /+1,"): $data{'Species'}\n"}
    if(exists $data{'Num. atoms'}){print "\tThere are $data{'Num. atoms'} atoms.\n"}
    if(exists $data{'Basis type'}){print "\t$data{'Basis type'} pseudopotentials.\n"}
    if(exists $data{'Symmetry'}){print "\t$data{'Symmetry'}\n"}
    
    # Electronic data:
    if($options{$invocation}{'q'}[0]>3){print "\n\t**ELECTRONS**\n";}	
    if(exists $data{'Num. electrons'}){
	print "\tThere are $data{'Num. electrons'} electrons, spin ",(($data{'Spin'}==1)?"averaged":($data{"autospin"}?"polarised (***magnetic***)":"polarised")),".\n";
    }
    if(exists $data{'Spin'}){
	if($data{'Spin'}==1){
	    printf "\t\tAv: $data{'Electronic levels (1)'}%s\n",
	    ($data{'Metallic'}?(sprintf " (metallic %.4f)",$data{'mue 1'}):"");
	    @esum=split" ",$data{'Electronic levels (1)'};
	    $esum=$esum[0]*2;
	    for(2..$esum[1]+1){$esum+=$esum[$_]}
	    if(abs((eval(sprintf"%.0f",$esum))-$esum)>0.01&&!$data{"Esum format error"}){print"\t\t\a** Warning - non-integer no. of electrons (",abs(int($esum)-$esum),") **\n"}
	}else{
	    for(1..2){
		print "\t\t",(($_-1)?"Dn: ":"Up: ");
		printf "%s%s%s\n",
		($data{'autospin'}?
		 ($data{'muB'}?
		  ($data{'Num. electrons'}+($_-1?-1:1)*$data{'muB'})*0.5
		  :
		  "?"
		 )
		 :
		 $data{"Electronic levels ($_)"}),
		($data{'Metallic'}?(sprintf " (metallic %.4f)",$data{"mue $_"}):"");
		@esum=split" ",$data{"Electronic levels ($_)"};
		$esum=$esum[0];for(2..$esum[1]+1){$esum+=$esum[$_]}
		if(abs((eval(sprintf"%.0f",$esum))-$esum)>0.01&&!$data{"Esum format error"}){print"\t\t\a** Warning - non-integer no. of electrons (",abs(int($esum)-$esum),") **\n"}
	    }
	}
	#Check for esum error:
	$ThisK=1;
	$ThisSpin=1;
	if(@ { $data{'esum'} }){
	    for$k(0..  $# { $data{'esum'} }){
		$_= $ { $data{'esum'} } [$_];
		if($ThisSpin==1){$esum=$data{'Electronic levels (1)'}}else{$esum=$data{'Electronic levels (2)'}}
		@esum=split" ",$esum;
		$esum=$esum[0];if($data{'Spin'}==1){$esum*=2}
		for(2..$esum[1]+1){$esum+=$esum[$_]}
		if(abs($_-$esum)>0.001&&!$data{'Metallic'}){
		    $error++;
		    printf "\t\a**** Potential error in electron count ($ThisK)! Is this a metallic run? ****\n".
			"\t**** Found %9.4f electrons where there should be %9.4f! ****\n",$_,$esum;last
		}
		$ThisK++;
		if($ThisK>$data{'Num. k-points'}){
		    $ThisK=1;
		    if($data{'Spin'}==2&&$ThisSpin==1){$ThisSpin=2}else{$ThisSpin=1}
		}
	    }
	}
    }
    if(exists $data{"restart write"}||exists $data{"restart read"}){
	print "\tRestart Dump: ";
	if(exists $data{"restart read"}){print "READ",
					 ($data{"restart read"}eq"T"?
					  "(ovrrdpsns)":"");
					 if(exists $data{"restart write"}){print "/"}
	}
	if(exists $data{"restart write"}){print "WRITE"}
	print "\n";
    }
    if(exists $data{"RSB"}){print "\tReal space build (gvec cut-off = ",($data{"gvec_cutoff"}?$data{"gvec_cutoff"}:"default"),")\n"}
    if(exists $data{'Charge state'}){print "\tCharged system: $data{'Charge state'}\n"}
    if(exists $data{'EXC'}){print"\tFunctional = $data{EXC}\n"}
    if(exists $data{'Temperature'}){
	print "\tElectronic temperature = $data{'Temperature'} eV (".($data{'Smearing'}?$data{'Smearing'}:"Fermi").")".(($data{'Temperature'}>0.1&&$data{'Smearing'}ne"methpax")?"**too high?!**":"")."\n";
    }
    print "\tndim = ".($data{'Basis ndim'}?$data{'Basis ndim'}:"?").", nfit = ".($data{'Basis nfit'}?$data{'Basis nfit'}:"?")."\n";
    if(exists $data{'Charge Density option'}){print "\tCharge density type = $data{'Charge Density option'}\n";}
    if(exists $data{'Num. bcs'}){
	print "\t$data{'Num. bcs'} bond-centres detected".
	    ($data{'Num. bcs'}/$data{'Num. atoms'}>2.2?" (too many?)":"").
	    ($data{'Num. bcs'}/$data{'Num. atoms'}<1.8?" (too few?)":"").
	    ".\n";
    }elsif(exists $data{'Num. bcs detected'}){
	print "\t$data{'Num. bcs detected'} bond-centres detected [not included]".
	    ($data{'Num. bcs detected'}/$data{'Num. atoms'}>2.2?" (too many?)":"").
	    ($data{'Num. bcs detected'}/$data{'Num. atoms'}<1.8?" (too few?)":"").
	    ".\n";
    }
    if(exists $data{'Ecut'}){print "\tEcut = $data{'Ecut'} Ha, FFT grid = ",(join"x",@{$data{'FFT grid'}}),"\n";}
    
    # Job info:
    if($options{$invocation}{'q'}[0]>3){print "\n\t**JOB**\n";}	
    print "\t$data{'Optimise'}";
    if(exists $data{'Num. iteration'}){print " ($data{'Num. iteration'} iteration".($data{'Num. iteration'}-1?"s":"").")\n"}else{print ".\n"}
    if(exists $data{'NEB'}){
	printf "\tNEB: imgs=%d  passes=%d  nopt=%d  clmb=%d  pth=%s\n",
	$data{'NEB nimages'},$data{'NEB passes'},$data{'NEB nopt'},$data{'NEB climb'},$data{'NEB path'};
    }
    if(exists $data{'dds'}){
	print "\tEnergy double derivs: ",(join " ",@{$data{'dds'}});
	if($data{'DDS'}){print " (completed).\n"}
	elsif($data{'REC'}){
	    $a=$data{'REC'}=~s/deriv/deriv/g;
	    printf " (restart, %2.0f%s done).\n",$a*100/3./(split" ",$data{"2DD"}),'%';
	}
	else{print " (s'mt went wrong).\n"}
	    if($data{"2DD"}){
		my @a=(split" ",$data{"2DD"});
		my $trip=1;
		printf "\tUniques: %3d independent atom sites as follows\n\t        ",$#a+1;
		for(0..$#a){
		    printf" %3d",$a[$_];
		    if($_!=$#a && $trip==15){
			$trip=0;
			print"\n\t        ";
		    }
		    $trip++;
		}
		print "\n"
	    }
    }
    if(exists $data{'Mulliken analysis'}){print "\tMulliken analysis, levels $data{'Mulliken analysis'}\n"}
    if(exists $data{'optexp'}){
	print "\tExponent optimisation (types $data{'optexp'}): ",$#{$data{'ABC'}}+1," energies\n"
    }
    if(exists $data{"Bulk modulus au"}){
	printf "\tOptimised a0 = %8.6f au (egy=%.5f au)\n\tBulk modulus = %8.6f au (%.1f GPa)\n",$data{'Optimised a0'},
	$data{"Optimised energy"},$data{'Bulk modulus au'},$data{'Bulk modulus au'}*29410;
    }


    # Lattice data:
    if(exists $data{'lattice type'}||exists $data{'lattice vecs'}){
	if($options{$invocation}{'q'}[0]>3){print "\n\t**PERIODICITY**\n";}
	if($data{"lattice params"}){
	    $data{'lattice params'}=~s/\s+/ /g;
	    print "\tInput param(s) = $data{'lattice params'} au.".
		($data{'lattice type'}?" ($data{'lattice type'})\n":"\n");
	}else{
	    print "\tInput a0 = $data{'lattice a0'} au.".
		($data{'lattice type'}?" ($data{'lattice type'})\n":"\n");
	}
	if($data{'lattice vecs'}&&$options{$invocation}{'q'}[0]>2){
	    print "\tLattice Vectors:\n";
	    @d=(split" ",$data{'lattice vecs'});
	    print"\t\ta1 = (",$d[0],",",$d[1],",",$d[2],")\n";
	    print"\t\ta2 = (",$d[3],",",$d[4],",",$d[5],")\n";
	    print"\t\ta3 = (",$d[6],",",$d[7],",",$d[8],")\n";
	}
	print "\tBZ-sampling: $data{'Num. k-points'} k-point".
	    (($data{'Num. k-points'}>1)?"s":"").
	    (($data{'use_kpar'})?" (kpar)":"").
	    (($data{'k-points'}[0]=~/rel/)?" (rel)":"").
	    (($options{$invocation}{'q'}[0]>2)?":\n":".\n")
	    ;
	if($options{$invocation}{'q'}[0]>2){
	    for(0..($data{'Num. k-points'}-1)){print (join" ","\t\t",(split" ",$ { $data{'k-points'} }[$_])[0..3],"\n");}
	}
	if($#{ $data{'k-points'} }>=$data{'Num. k-points'}){
	    print "\tBandstructure Sampling (",$#{ $data{'k-points'} }-$data{'Num. k-points'}+1,
	    " point".(($#{ $data{'k-points'} }-$data{'Num. k-points'}>0)?"s":"").")\n";
	    if($options{$invocation}{'q'}[0]>3){
		for($data{'Num. k-points'}..$#{ $data{'k-points'} }){
		    print (join" ","\t\t",(split" ",$ { $data{'k-points'} }[$_])[0..3],"\n");
		}
	    }
	}
    }
    
    # Energy data:
    if($options{$invocation}{'q'}[0]>3){print "\n\t**ENERGY**\n";}	
    if($options{$invocation}{'q'}[0]>2){
	if(exists $data{'Final energy mc,'}){printf "\tFinal energy = %12.5f au (mid-S/C) [echerr=%.2e]\n",$data{'Final energy mc,'},$data{"echerr $data{'point data'}"}}
    }
    if(exists $data{'Final energy egy'}){printf "\tFinal energy = %12.5f au (S/C) [echerr=%.2e]\n",$data{'Final energy egy'},$data{"echerr "}}
    if(exists $data{'Final energy'}&&!exists $data{'Final energy egy'}){printf "\tFinal energy = %12.5f au (linemin)\n",$data{'Final energy'}}
    if($options{$invocation}{'q'}[0]>3){
	if(exists $data{'Energy components'}){
	    if($data{'Energy components'}[1]==$data{'Final energy'}){
		for(0..$#{$data{'Energy components'}}-1){
		    printf "\t      %6s = %12.5f au\n",$data{'Energy terms'}[$_],$data{'Energy components'}[$_+1];
		}
	    }}
    }
    @d=(split" ",$data{'Energy shiftt'});if(!$#d&&$d[0]=~/\*(.*)/){@d=($1,$1);}
    my $shifty=($data{"backward"}?0:($d[1]-$d[0]));
    my $thisenergy=0;
    if(exists $data{'Final energy'}&&!exists $data{'Final energy egy'}){
	$thisenergy=$data{'Final energy'};
    }elsif(exists $data{'Final energy egy'}){
	$thisenergy=$data{'Final energy egy'};
    }elsif(exists $data{'Final energy mc,'}){
	$thisenergy=$data{'Final energy mc,'};
    }
    if($#{$data{'NEB energies'}[$data{'NEB iter'}]}>-1){ 
	printf "\tNEB Energies (iter %d):\n\t\t%4s %12s %9s %9s %9s\n",$data{"NEB iter"},"img","E(Ha)","E_rel(eV)","F_image","F_raw";
	printf "\t\t%4s %12s %9s %9s %9s\n","====","============","=========","=========","=========";
	for my $e (@{$data{'NEB energies'}[$data{'NEB iter'}]}){
	    my@e=(split" ",$e);
	    printf "\t\t%4d %12.5f %9.5f %9.5f %9.5f %s\n",@e,($e[0]==$data{'NEB saddle image'}[$data{"NEB iter"}]?"<- saddle":"");
	}
    }else{
	printf "\t      SHIFTT(rel) += %9.5f au -> Etot = %11.5f au\n",
	$shifty,$shifty+$thisenergy;
    }
    if($data{"backward"}){
	printf "\t      Backward compatible energy  -> Ebak = %11.5f au\n",
	($d[1]-$d[0])+$thisenergy;
    }
    
    if(exists $data{'Energy change'}){
	print "\t      (last change = $data{'Energy change'} eV, rel egy = $data{'Relative energy'} eV)\n";
	print "\t      (max. force  =  $data{'Maximum force'} au)\n";
    }
    if(!exists $data{'mcmax'}){printf "\a\t*****Not self-consistent  [echerr=%.2e]*****\n",$data{"echerr $data{'point data'}"};$error++}
    
    # Error messages:
    
    if(exists $data{'not converged'}){print "\a\t*****Not converged iter: $data{'not converged'}*****\n"}
    if(exists $data{'DIIS warning'}){print "\a\t***** DIIS warning detected in output *****\n"}
    if($data{'starting banner'}>1){print "\a\t***** $data{'starting banner'} starting banners detected - probable concatenation of outputs *****\n"}
    
    # Gres settings:
    if($options{$invocation}{'q'}[0]>3){print "\n\t**GRES**\n";}
    if($options{$invocation}{'q'}[0]>2){
	print "\tXYZ viewer set to '$options{$invocation}{'xyz'}[0]'\n";
	print "\tFile over-writing ".($options{$invocation}{'over'}[0]?"enabled\n":"supressed\n");
    }
    
    #If there are more files, add a space:
    if($file ne $files[$#files]){print "\n"}
    
}

######################################################################
#### List the new files generated and their contents: ################
######################################################################
sub FileSummary{
    if($options{$invocation}{'q'}[0]>3){print "\n\t**FILES**\n"}
    # Work out the space needed for the descriptions:
    $l=11;
    for(keys %OpenFiles){
	next if $_ eq "RES";
	$l=(length($OpenFiles{$_}[1])>$l)?length($OpenFiles{$_}[1]):$l;
    }
    # Print them out:
    for $k (keys %OpenFiles){
	next if $k eq "RES";
	print" "x(8+$l-length($OpenFiles{$k}[1])),"$OpenFiles{$k}[1]: $OpenFiles{$k}[0]\n";
	# Also output additional comments if they exist:
	if($#{$OpenFiles{$k}}>1){
	    for(@ { $OpenFiles{$k} }[2..$#{$OpenFiles{$k}}]){print " "x($l-length($root{$k})-7),"\a!$root{$k} file creation: $_!\n";}
	}
    }
    #Now for comments for files NOT opened:
    for $k (keys %FileComments){
	for(@ { $FileComments{$k}}){
	    print " "x($l-length($root{$k})),"!$root{$k} ($k) file creation: $_!\n";
	}
    }
}

#####   #####      #    #    #   #####
#    #  #    #     #    ##   #     #
#    #  #    #     #    # #  #     #
#####   #####      #    #  # #     #
#       #   #      #    #   ##     #
#       #    #     #    #    #     #

######################################################################
#### Output the xyz to file ##########################################
######################################################################
sub PrintXYZFile{
    #Input is the # of the iteration to output - if '-1' is passed
    #then all OTB are output.
    die "Wrong number of arguments supplied to PrintXYZFile\n" if $#_;
    my $iter = $_[0];
    if($iter!=-1&&($iter>$data{'OTBSet'}||$iter<1)){die "Passed an iteration number out of range ($iter) in PrintXYZFile\n"}
    if(!exists $data{'Species'}){die "Arrived in PrintXYZFile without detecting atomic species\n"}
    @species=split " ",$data{'Species'};
    print "!DBG! In PrintXYZFile\n" if $options{$invocation}{'debug'}[0];
    #Output all XYZ:
    if($iter<0){
	if(exists $data{'DiffPoint'} && !$options{$invocation}{v}[0]){
	    my $f=OpenOutput(XYZ,"new",$tag,"diff","Diffusion point iterations");
	    if(!$f){return}
	    my $i;
	    while(@{$data{'DiffPoint'}}){
		$i=shift@{$data{'DiffPoint'}};
		PrintXYZ($i);
	    }
	}else{
	    my $f=OpenOutput(XYZ,"new",$tag,"all","All iterations");
	    if(!$f){return}
	    my $i=1;while($i<=$data{'OTBSet'}){PrintXYZ($i);++$i}
	}
    }else{
	#Output specific XYZ:
	if($iter==1){
	    my $f=OpenOutput(XYZ,"new",$tag,"init","otb set $iter");	    
	    if(!$f){return}
	    PrintXYZ($iter);
	}
	elsif($iter==$data{'OTBSet'}){
	    my $f=OpenOutput(XYZ,"new",$tag,"final","otb set $iter");
	    if(!$f){return}
	    PrintXYZ($iter);
	}
	else{
	    my $f=OpenOutput(XYZ,"new",$tag,"init","otb set $iter");
	    if(!$f){return}
	    PrintXYZ($iter);
	}
    }
    #If requested, visualise the structure:
    if($options{$invocation}{'x'}[0]||
       $options{$invocation}{'xlast'}[0]||
       $options{$invocation}{'xinit'}[0]){
	push @{$system{'xyz'}},$f;
    }
}

######################################################################
#### Print out the XYZ lines in an appropriate format: ###############
######################################################################
sub PrintXYZ{
    my @LV=();
    my $iter=$_[0];
    print XYZ "$data{'Num. atoms'}\n#Set no. $iter".
	(($iter==$data{'OTBSet'})?" (Final)":"").
	(($iter==1)?" (Initial)\n":"\n");
    # Loop over the number of atoms in the cluster/cell
    my $n=0;my @d=();for(@{$data{'otb'}[$iter]}){
	if($iter==1){$d[++$n]=$_}
	else{$d[(split)[0]]=$_;}
    }
    # Specify the lattice vectors:
#    if($iter==1){
#	@LV=@{ $data{"d-latt P"} }
#
    if(exists $data{"d-latt P $iter"}){
	@LV=@{$data{"d-latt P $iter"}};
    }else{
	@LV=@{ $data{"d-latt P"} }
    }
#    printf "#---> %d @LV (%f)\n",$iter,$data{"d-latt P $iter"}[0];
    my $a=0;while(++$a<=$data{'Num. atoms'}){
	if($data{"unit definition"} eq "atomic"
	   ||
	   ($data{"unit definition"} eq "internal"&&$data{"restart options override-positions"}&&$iter>1)
	   ||
	   #Old output where all but internal coords are rescaled to atomic during output:
	   ($data{"rescaled positions"}&&$iter!=1&&($data{"unit definition"} ne "internal"))
	   ||
	   #Old output where all but internal coords are rescaled to atomic during output:
	   ($iter!=1 && $data{"unit definition"}=~/\d/)
	    ){
	    if($d[$a]){
		@p=((split" ",$d[$a])[1],(split" ",$d[$a])[6..8]);
		$p[0]=$species[$p[0]-1];
		for(1..3){$p[$_]*=$const{'autoang'}}
		printf XYZ (FormatXYZ(@p));
	    }else{
		@p=((split" ",$data{'otb'}[1][$a-1])[1],
		    (split" ",$data{'otb'}[1][$a-1])[6..8]);
		$p[0]=$species[$p[0]-1];
		for(1..3){$p[$_]*=$const{'autoang'}}
		printf XYZ (FormatXYZ(@p));
	    }
	}elsif($data{"unit definition"} eq "relative"){
	    if($d[$a]){
		@p=((split" ",$d[$a])[1],(split" ",$d[$a])[6..8]);
		$p[0]=$species[$p[0]-1];
		if($iter==1){my$a=(split" ",$data{"lattice params"})[0];for(1..3){$p[$_]*=$a}}
		for(1..3){$p[$_]*=$const{'autoang'}}
		printf XYZ (FormatXYZ(@p));
	    }else{
		@p=((split" ",$data{'otb'}[1][$a-1])[1],
		    (split" ",$data{'otb'}[1][$a-1])[6..8]);
		$p[0]=$species[$p[0]-1];
		if($iter==1){my$a=(split" ",$data{"lattice params"})[0];for(1..3){$p[$_]*=$a}}
		for(1..3){$p[$_]*=$const{'autoang'}}
		printf XYZ (FormatXYZ(@p));
	    }
	}elsif($data{"unit definition"}=~/^ang/){
	    if($d[$a]){
		@p=((split" ",$d[$a])[1],(split" ",$d[$a])[6..8]);
		$p[0]=$species[$p[0]-1];
		printf XYZ (FormatXYZ(@p));
	    }else{
		@p=((split" ",$data{'otb'}[1][$a-1])[1],
		    (split" ",$data{'otb'}[1][$a-1])[6..8]);
		$p[0]=$species[$p[0]-1];
		printf XYZ (FormatXYZ(@p));
	    }
	}elsif($data{"unit definition"}=~/^\d/){
	    if($d[$a]){
		@p=((split" ",$d[$a])[1],(split" ",$d[$a])[6..8]);
		$p[0]=$species[$p[0]-1];
		for(1..3){$p[$_]*=($data{"unit definition"}*$const{'autoang'})}
		printf XYZ (FormatXYZ(@p));
	    }else{
		@p=((split" ",$data{'otb'}[1][$a-1])[1],
		    (split" ",$data{'otb'}[1][$a-1])[6..8]);
		$p[0]=$species[$p[0]-1];
		for(1..3){$p[$_]*=($data{"unit definition"}*$const{'autoang'})}
		printf XYZ (FormatXYZ(@p));
	    }
	}elsif($data{"unit definition"} eq "int-p"||$data{"unit definition"} eq "internal"){
	    if($d[$a]){
		@p=(
		    (split" ",$d[$a])[1],
		    INT2XYZ(
			(split" ",$d[$a])[6..8],
			@LV
		    )
		    );
		$p[0]=$species[$p[0]-1];
		for(1..3){$p[$_]*=$const{'autoang'}}
		printf XYZ (FormatXYZ(@p));
	    }else{
		@p=((split" ",$data{'otb'}[1][$a-1])[1],
		    INT2XYZ(
			(split" ",$data{'otb'}[1][$a-1])[6..8],
			@LV
		    )
		    );
		$p[0]=$species[$p[0]-1];
		for(1..3){$p[$_]*=$const{'autoang'}}
		printf XYZ (FormatXYZ(@p));	    
	    }
	}elsif($data{"unit definition"} eq "int-c"){
	    if($d[$a]){
		@p=(
		    (split" ",$d[$a])[1],
		    INT2XYZ(
			(split" ",$d[$a])[6..8],
			@{ $data{"d-latt C"} }
		    )
		    );
		$p[0]=$species[$p[0]-1];
		for(1..3){$p[$_]*=$const{'autoang'}}
		printf XYZ (FormatXYZ(@p));
	    }else{
		@p=((split" ",$data{'otb'}[1][$a-1])[1],
		    INT2XYZ(
			(split" ",$data{'otb'}[1][$a-1])[6..8],
			@{$data{"d-latt C"}}
		    )
		    );
		$p[0]=$species[$p[0]-1];
		for(1..3){$p[$_]*=$const{'autoang'}}
		printf XYZ (FormatXYZ(@p));	    
	    }
	}else{
	    die "I really shoulnd't get here!\nUnit definition: '$data{'unit definition'}'\n";
	}
    }
}

######################################################################
#### Convert a,b,c in relative to a,b,c in carts #####################
######################################################################
sub INT2XYZ{
    if($#_-11){die "\a\tFatal Error - wrong number of terms ($#_!=11) passed to \"INT2XYZ\"\n@_\n"}
    my @r=@_[0..2];
    my @vec=@_[3..11];
    my @xyz=(0,0,0);
    for $a (0..2){
	for $b (0..2){
	    $xyz[$a]+=$vec[$a+3*$b]*$r[$b];
	}
    }
    return(@xyz)
}

####   ######   #####
#    #  #          #
#       #####      #
#  ###  #          #
#    #  #          #
####   ######     #

######################################################################
#### Get the evals from the output ###################################
######################################################################
sub GetEvals{
    if($#_){die "Wrong number of parameters passed to GetEvals ($#_!=1)\n"}
    my ($type,$esum)=($_[0],0);
    print "!DBG! Getting evals, type = $type\n" if $options{$invocation}{'debug'}[0];
    #While one is reading lines starting with a number, add them to
    #the current list of evals
    if(($type eq "evals") or ($type eq "eval") or ($type eq "unoccupied") or ($type eq "k-point")){
	while(($_=<RES>)=~/^\s*-?\d{0,3}\.\d+/&&!eof){
	    next if /^\s*[!%]/;
	    if(/^\s*[\d\.\-]/){
		push @ { $data{'evals'}[$data{'EvalSet'}] },(split);
	    }
	}
    }elsif($data{"screened exchange"}&&$type eq "kpoint"){
	my ($t,$first,$outofthree)=(0,1,0);
	while(($_=<RES>)=~/^(\s*\d{1,3}\s|\s*-?\.?\d|\*\*\*\s+)/&&!eof){
	    next if /^\s*[!%]/;
	    if($_!~/\S/){last}
	    my @e=split;
	    if($first){if($e[0]=~/^\d+$/){$t=1}$first=0}
	    if($t==1&&$e[0]=~/^([0-9]+|\**)$/){		
		push @ { $data{'evals'}[$data{'EvalSet'}+$outofthree] },@e[1..$#e];
		$outofthree++;
		if($outofthree==3){$outofthree=0}
	    }elsif(!$t){
		push @ { $data{'evals'}[$data{'EvalSet'}+$outofthree] },@e;
		$outofthree++;
		if($outofthree==3){$outofthree=0}
	    }
	    if($t==1&&$e[0]=~/^-?[012]{0,1}\.\d+$/){		
		for(@e){$esum+=$_}
	    }
	}	
	$data{'EvalSet'}+=2;
    }elsif(($type eq "kpoint") or ($type eq "min") or ($type eq "max") or ($type eq "avg")){
	my ($t,$first)=(0,1);
	while(($_=<RES>)=~/^(\s*\d{1,3}\s|\s*-?\.?\d|\*\*\*\s+)/&&!eof){
	    next if /^\s*[!%]/;
	    if($_!~/\S/){last}
	    my @e=split;
	    if($first){if($e[0]=~/^\d+$/){$t=1}$first=0}
	    if($t==1&&$e[0]=~/^([0-9]+|\**)$/){		
		push @ { $data{'evals'}[$data{'EvalSet'}] },@e[1..$#e];
	    }elsif(!$t){
		push @ { $data{'evals'}[$data{'EvalSet'}] },@e;
	    }
	    if($t==1&&$e[0]=~/^-?[012]{0,1}\.\d+$/){		
		for(@e){$esum+=$_}
	    }
	}
	if(/ALLOCATED|time/){$data{"Esum format error"}=1}
    }
    if($esum){push @ { $data{"esum"} },$esum}
    if($options{$invocation}{'debug'}[0]){print "DGB: e-sum=$esum\n"}
}

######################################################################
#### Get the OTB from the output #####################################
######################################################################
sub GetOTB{
    print "!DBG! Getting OTB\n" if $options{$invocation}{'debug'}[0];
    #While one is reading lines starting with a number, add them to
    #the current list of atom positions    
    while(<RES>){
	if(/(^\s*[!%]|^\s*$)/){
	    next;
	}elsif(
	    /^\s*\d+\s+\d+\s+-?\d+\s+-?\d+\s+-?\d+\s+-?\d+\s+-?(\d+\.?\d*|\d*\.\d+)\s+-?(\d+\.?\d*|\d*\.\d+)\s+-?(\d+\.?\d*|\d*\.\d+)\s*/){
	    push @ { $data{'otb'}[$data{'OTBSet'}] },$_;
	}elsif(
	    #Allow for scientific notation in the positions
	    /^\s*\d+\s+\d+\s+-?\d+\s+-?\d+\s+-?\d+\s+-?\d+\s+-?(\d+\.?\d*|\d*\.\d+)([ed][+-][0-9]+)?\s+-?(\d+\.?\d*|\d*\.\d+)([ed][+-][0-9]+)?\s+-?(\d+\.?\d*|\d*\.\d+)([ed][+-][0-9]+)?\s*/){
	    push @ { $data{'otb'}[$data{'OTBSet'}] },$_;
	}else{last;}
    }
    return @ { $data{'otb'}[$data{'OTBSet'}] } ;
}

######################################################################
#### Get the double derivitives from the output ######################
######################################################################
sub GetSpecies{
    print "!DBG! Getting species\n" if $options{$invocation}{'debug'}[0];
    #While one is reading lines starting with a number, add them to
    #the current list
    while(($_=<RES>)!~/end/&&!eof){
	if(/^\s*[!%]/){next}
	if(/GHOST/){$data{'Species'}.=" X "}	   
	elsif(!/pot=/&&/\{([a-z]{1,2})/i){$data{'Species'}.=ucfirst($1)." ";}
	elsif(/\{pot\s*=\s*[\d\.]+-([a-z]{1,2})/i){$data{'Species'}.=ucfirst($1)." ";}
	elsif(/\{pot\s*=\s*([a-z]{1,2})/i){$data{'Species'}.=ucfirst($1)." ";}
	elsif(/\{\d+-([a-z]{1,2})/i){$data{'Species'}.=ucfirst($1)." ";}
#        if(/\{/&&/\s*(\S+)\s*/i){push @ { $data{'Basis'} },$1."\n";}
        if(/\{/&&/\s*(\S.*\S)\s*$/i){push @ { $data{'Basis'} },$1."\n";}
    }
    chop($data{'Species'});
    return;
}

######################################################################
#### Get the lattice definition from the data input ##################
######################################################################
sub GetLatticeVectors{
    print "!DBG! Getting lattice vector from output data\n" if $options{$invocation}{'debug'}[0];
    #While one is reading lines starting with a number, add them to
    #the current list
    my $type = $_[0]; # P(rimitive) or C(onventional)
    #Sometimes (where the lattice is being detected) the data appears twice:
    if(exists $data{"d-latt $type"}){
	delete $data{"d-latt $type"};
	delete $data{"r-latt $type"};
    }
    while(($_=<RES>)!~/end/&&!eof){
	if(/^\s*[!%]/){next}
	chomp;
	my @a=(split);
	push @ { $data{"d-latt $type"} },@a[0..2];
	push @ { $data{"r-latt $type"} },@a[3..5];
	if( $#{  $data{"r-latt $type"} } == 8){last}
    }
    return;
}

sub FormatOTB{die "Error in FormatOTB" if ($#_);return (sprintf"%4d%2d%5d%5d%5d%5d%17.10f%17.10f%17.10f\n",(split " ",$_[0]))}
sub FormatXYZ{die "Error in FormatXYZ" if ($#_-3);return (sprintf"%2s%18.11f%18.11f%18.11f\n",@_)}
sub BubbleSort{
    my ($c,@a)=(1,@_);
    while($c<@a){my $p=1;while($p<@a){if($a[$p-1]>$a[$p]){@a[$p-1,$p]=@a[$p,$p-1];}$p++;}$c++}
    return @a;
}

######################################################################
#### Versio 57+ lattice definitions ##################################
######################################################################

sub LatticeDefinitions{
    #Up to six parameters to define the lattice:
    my $type=$_[0];
    my $orient=$_[1]-1;
    my @scale=(split" ",$_[2]);
    
    if(!$#scale){$scale[1]=$scale[2]=$scale[0]}
    
    my @p=@_[3..$#_];
    
    my %primitive=(
	"cub-p" => [$p[0],0,0,
		    0,$p[0],0,
		    0,0,$p[0]],
	"cub-i" => [-0.5*$p[0],0.5*$p[0],0.5*$p[0],
		    0.5*$p[0],-0.5*$p[0],0.5*$p[0],
		    0.5*$p[0],0.5*$p[0],-0.5*$p[0]],
	"cub-f" => [0.5*$p[0],0.5*$p[0],0,
		    0,0.5*$p[0],0.5*$p[0],
		    0.5*$p[0],0,0.5*$p[0]],
	"tet-p" => [$p[0],0,0,
		    0,$p[0],0,
		    0,0,$p[1],
		    0.5*$p[0],0.5*$p[0],0,
		    -0.5*$p[0],0.5*$p[0],0,
		    0,0,$p[1]],
	"tet-i" => [-0.5*$p[0],0.5*$p[0],0.5*$p[1],
		    0.5*$p[0],-0.5*$p[0],0.5*$p[1],
		    0.5*$p[0],0.5*$p[0],-0.5*$p[1],
		    -0.5*$p[0],0,0.5*$p[1],
		    0.5*$p[0],0,0.5*$p[1],
		    0,-0.5*$p[0],-0.5*$p[1]],
	"ort-p" => [$p[0],0,0,
		    0,$p[1],0,
		    0,0,$p[2]],
	"ort-i" => [-0.5*$p[0],0.5*$p[1],0.5*$p[2],
		    0.5*$p[0],-0.5*$p[1],0.5*$p[2],
		    0.5*$p[0],0.5*$p[1],-0.5*$p[2]],
	"ort-c" => [0.5*$p[0],0.5*$p[1],0,
		    -0.5*$p[0],0.5*$p[1],0,
		    0,0,$p[2]],
	"ort-f" => [0.5*$p[0],0.5*$p[1],0,
		    0.5*$p[0],0,0.5*$p[2],
		    0,0.5*$p[1],0.5*$p[2]],
	"mon-p" => [$p[0],0,0,
		    0,$p[1],0,
		    $p[2]*sin($p[3]),0,$p[2]*cos($p[3])],
	"mon-c" => [0.5*$p[0],-0.5*$p[1],0,
		    0.5*$p[0],0.5*$p[1],0,
		    $p[2]*sin($p[3]),0,$p[2]*cos($p[3])],
	"trc-p" => [$p[0],0,0,
		    $p[1],$p[2],0,
		    $p[3],$p[4],$p[5]],
	"trg-r" => [
	    $p[0],$p[1],$p[1],
	    $p[1],$p[0],$p[1],
	    $p[1],$p[1],$p[0],
	    $p[1],0,$p[0],
	    -0.5*$p[1],0.5*sqrt(3)*$p[1],$p[0],
	    -0.5*$p[1],-0.5*sqrt(3)*$p[1],$p[0],
	    $p[0]*sin($p[1]),0,$p[0]*cos($p[1]),
	    -0.5*$p[0]*sin($p[1]),0.5*sqrt(3)*$p[0]*sin($p[1]),$p[0]*cos($p[1]),
	    -0.5*$p[0]*sin($p[1]),-0.5*sqrt(3)*$p[0]*sin($p[1]),$p[0]*cos($p[1]),
	    $p[0]*(1+$p[1]),$p[0]*$p[1],$p[0]*$p[1],
	    $p[0]*$p[1],$p[0]*(1+$p[1]),$p[0]*$p[1],
	    $p[0]*$p[1],$p[0]*$p[1],$p[0]*(1+$p[1])
	],
	"hex-p" => [
	    $p[0],0,0,
	    -0.5*$p[0],0.5*sqrt(3)*$p[0],0,
	    0,0,$p[1],
	    0.5*$p[0],-0.5*sqrt(3)*$p[0],0,
	    0.5*$p[0],0.5*sqrt(3)*$p[0],0,
	    0,0,$p[1]
	]
	);
    my %conventional=(
	"cub-p" => [$p[0],0,0,
		    0,$p[0],0,
		    0,0,$p[0]],
	"cub-i" => [$p[0],0,0,
		    0,$p[0],0,
		    0,0,$p[0]],
	"cub-f" => [$p[0],0,0,
		    0,$p[0],0,
		    0,0,$p[0]],
	"tet-p" => [$p[0],0,0,
		    0,$p[0],0,
		    0,0,$p[1],
		    $p[0],0,0,
		    0,$p[0],0,
		    0,0,$p[1]],
	"tet-i" => [$p[0],0,0,
		    0,$p[0],0,
		    0,0,$p[1],
		    $p[0],0,0,
		    0,$p[0],0,
		    0,0,$p[1]],
	"ort-p" => [$p[0],0,0,
		    0,$p[1],0,
		    0,0,$p[2]],
	"ort-i" => [$p[0],0,0,
		    0,$p[1],0,
		    0,0,$p[2]],
	"ort-c" => [$p[0],0,0,
		    0,$p[1],0,
		    0,0,$p[2]],
	"ort-f" => [$p[0],0,0,
		    0,$p[1],0,
		    0,0,$p[2]],
	"mon-p" => [$p[0],0,0,
		    0,$p[1],0,
		    $p[2]*sin($p[3]),0,$p[2]*cos($p[3])],
	"mon-c" => [$p[0],0,0,
		    0,$p[1],0,
		    $p[2]*sin($p[3]),0,$p[2]*cos($p[3])],
	"trc-p" => [$p[0],0,0,
		    $p[1],$p[2],0,
		    $p[3],$p[4],$p[5]],
	"trg-r" => [
	    $p[0],$p[1],$p[1],
	    $p[1],$p[0],$p[1],
	    $p[1],$p[1],$p[0],
	    $p[1],0,$p[0],
	    -0.5*$p[1],0.5*sqrt(3)*$p[1],$p[0],
	    -0.5*$p[1],-0.5*sqrt(3)*$p[1],$p[0],
	    $p[0]*sin($p[1]),0,$p[0]*cos($p[1]),
	    -0.5*$p[0]*sin($p[1]),0.5*sqrt(3)*$p[0]*sin($p[1]),$p[0]*cos($p[1]),
	    -0.5*$p[0]*sin($p[1]),-0.5*sqrt(3)*$p[0]*sin($p[1]),$p[0]*cos($p[1]),
	    $p[0]*(1+$p[1]),$p[0]*$p[1],$p[0]*$p[1],
	    $p[0]*$p[1],$p[0]*(1+$p[1]),$p[0]*$p[1],
	    $p[0]*$p[1],$p[0]*$p[1],$p[0]*(1+$p[1])
	],
	"hex-p" => [
	    $p[0],0,0,
	    -0.5*$p[0],0.5*sqrt(3)*$p[0],0,
	    0,0,$p[1],
	    0.5*$p[0],-0.5*sqrt(3)*$p[0],0,
	    0.5*$p[0],0.5*sqrt(3)*$p[0],0,
	    0,0,$p[1]
	]
	);
    
    #Pre-v57 definitions:
    @{ $primitive{"fcc"} }=(0.5*$p[0],0.5*$p[0],0,
			    0.5*$p[0],0,0.5*$p[0],
			    0,0.5*$p[0],0.5*$p[0]);
    @{ $conventional{"fcc"} }=(0.5*$p[0],0.5*$p[0],0,
			       0.5*$p[0],0,0.5*$p[0],
			       0,0.5*$p[0],0.5*$p[0]);
    @{ $primitive{"bcc"} }=@{ $primitive{"cub-i"} };
    @{ $conventional{"bcc"} }=@{ $primitive{"cub-i"} };
    @{ $primitive{"cubic"} }=@{ $primitive{"cub-p"} };
    @{ $conventional{"cubic"} }=@{ $primitive{"cub-p"} };
    @{ $primitive{"hex"} }=@{ $primitive{"hex-p"} }[0..8];
    #Turn "c/a" into "c":
    ${ $primitive{"hex"} }[8]*=$p[0];
    @{ $conventional{"hex"} }=@{ $primitive{"cub-p"} }[0..8];
    @{ $primitive{"rhomb"} }=(sqrt(3)*0.5*$p[0],-0.5*$p[0],0,
			      sqrt(3)*0.5*$p[0],0.5*$p[0],0,
    			      0,0,$p[1]*$p[0]);
    @{ $conventional{"rhomb"} }=(sqrt(3)*0.5*$p[0],-0.5*$p[0],0,
				 sqrt(3)*0.5*$p[0],0.5*$p[0],0,
				 0,0,$p[1]*$p[0]);
    
    
    my @vec=(@{$primitive{"$type"}}[(0+$orient*9)..(8+$orient*9)],@{$conventional{"$type"}}[(0+$orient*9)..(8+$orient*9)]);
    
    #Now apply the scaling:
    for $a (0..2){for $b (0..2){$vec[$b+$a*3]*=$scale[$a]}}
    
    return @vec;
    
}
